import { build } from 'esbuild';
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { mkdtemp, readFile, readdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const dir = await mkdtemp(join(tmpdir(), 'mjv-calendar-'));
const fixtures = {
 auth: `import {useState,useEffect} from 'react';const profile={id:'a',full_name:'Alice',organization_id:'org',role:'admin',has_calendar_access:true};export function useAuth(){const [ready,setReady]=useState(!new URLSearchParams(location.search).has('delayAuth'));useEffect(()=>{const t=setTimeout(()=>setReady(true),200);return()=>clearTimeout(t)},[]);return {user:{id:'a'},profile:ready?profile:null}};`,
 create: `import React from 'react';export function CreateAppointmentModal(props){return <div role="dialog" aria-label="Create event"><output data-testid="event-selection">{JSON.stringify({date:props.initialDate,start:props.initialTime,end:props.initialEndTime,technician:props.initialTechnicianId})}</output><button onClick={props.onClose}>Close event</button></div>}`,
 manage: `export function CalendarManagementModal(){return null}`,
 supabase: `const records={organizations:[{id:'org',timezone:'America/Chicago'}],profiles:[{id:'a',full_name:'Alice',role:'technician',is_technician:true,is_active:true}],work_orders:[{id:'wo',work_order_number:'100',title:'Installation',assigned_to:'a',scheduled_date:'2026-10-12',scheduled_start_time:'09:00',scheduled_end_time:'10:30',status:'assigned'}],tasks:[{id:'task',title:'Zero-duration reminder',reminder_date:'2026-10-12T16:00:00Z',assigned_to:'a',status:'pending'}]};
 const appointments=[{id:'apt',title:'Site visit',appointment_date:'2026-10-12',start_time:'09:15',end_time:'10:00',assigned_technician:'a',status:'scheduled',can_view_details:true},{id:'all',title:'All-day event',appointment_date:'2026-10-13',start_time:null,end_time:null,all_day:true,assigned_technician:'a',status:'scheduled',can_view_details:true}];
 appointments.push({id:'private',title:'Busy',appointment_date:'2026-10-12',start_time:'18:00',end_time:'19:00',assigned_technician:'a',status:'scheduled',is_private:true,can_view_details:false});records.appointments=appointments;export const supabase={auth:{async getSession(){return {data:{session:{user:{id:'a'}}}}},async getUser(){return {data:{user:{id:'a'}}}}},from(table){let single=false;const predicates=[];const q=new Proxy({},{get(_,key){if(key==='then')return(done,fail)=>Promise.resolve({data:single?(records[table]||[])[0]:(records[table]||[]).filter(r=>predicates.every(p=>p(r))),error:null}).then(done,fail);return(...args)=>{if(key==='single'||key==='maybeSingle')single=true;if(key==='insert')window.calendarWrites.push({table,value:args[0]});if(key==='is')predicates.push(r=>r[args[0]]==null);if(key==='eq')predicates.push(r=>r[args[0]]===args[1]);if(key==='gte')predicates.push(r=>r[args[0]]>=args[1]);if(key==='lte')predicates.push(r=>r[args[0]]<=args[1]);return q}}});return q},async rpc(name,args){window.calendarCalls.push({name,args});return {data:name.startsWith('reschedule_')?{success:true}:name==='get_appointments_with_privacy'?appointments.filter(a=>a.appointment_date>=args.p_start_date&&a.appointment_date<=args.p_end_date):[],error:null}},channel(){const c={on(){return c},subscribe(){return c},unsubscribe(){}};return c},removeChannel(){}};`,
};
const source=`import React from 'react';import {createRoot} from 'react-dom/client';import {AppointmentsCalendar} from './src/components/Appointments/AppointmentsCalendar';import {ResourceDayView} from './src/components/Dispatch/ResourceDayView';import {CreateAppointmentModal} from './src/components/Appointments/CreateAppointmentModal.tsx';window.calendarCalls=[];window.calendarWrites=[];createRoot(document.getElementById('root')).render(<main style={{maxWidth:1100,margin:'auto',padding:12}}>{new URLSearchParams(location.search).get('surface')==='dispatch'?<ResourceDayView onNavigate={(tab,params)=>{window.openedWorkOrder=params.workOrderId}}/>:new URLSearchParams(location.search).get('surface')==='appointment'?<CreateAppointmentModal calendarContext="technicians" initialDate="2026-10-12" initialTime="09:20" initialTechnicianId="a" onClose={()=>{window.appointmentClosed=true}} onSuccess={()=>{window.appointmentSaved=true}}/>:<AppointmentsCalendar onWorkOrderSelect={id=>{window.openedWorkOrder=id}}/>}</main>);`;
const server=createServer(async(req,res)=>{try{const file=req.url?.startsWith('/app.js')?'app.js':req.url?.startsWith('/style.css')?'style.css':'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(join(dir,file)))}catch{res.writeHead(404);res.end()}});
let browser;
try {
 await build({stdin:{contents:source,resolveDir:process.cwd(),loader:'tsx'},bundle:true,format:'iife',jsx:'automatic',outfile:join(dir,'app.js'),plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/lib\/supabase$|^\.\/supabase$/},()=>({path:'supabase',namespace:'fixture'}));b.onResolve({filter:/contexts\/AuthContext$/},()=>({path:'auth',namespace:'fixture'}));b.onResolve({filter:/\/CreateAppointmentModal$/},()=>({path:'create',namespace:'fixture'}));b.onResolve({filter:/\/CalendarManagementModal$/},()=>({path:'manage',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:fixtures[args.path],loader:'tsx',resolveDir:process.cwd()}))}}]});
 const css=(await readdir('dist/assets')).find(name=>name.startsWith('index-')&&name.endsWith('.css'));await writeFile(join(dir,'style.css'),(await readFile('dist/assets/'+css,'utf8')) + (await readFile(join(dir,'app.css'),'utf8')));await writeFile(join(dir,'index.html'),'<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script src="/app.js"></script></body></html>');
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const viewport of [{width:1280,height:900},{width:390,height:844},{width:320,height:568}]) {
  const page=await browser.newPage({viewport,timezoneId:'America/Los_Angeles'});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const url='http://127.0.0.1:'+server.address().port+'/calendar?popup=true&view=my&viewMode=week&date=2026-10-12';await page.goto(url);
  await page.getByText('Site visit',{exact:true}).waitFor();await page.getByText('Task: Zero-duration reminder',{exact:true}).waitFor();await page.getByText('All-day event',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Calendar date').inputValue(),'2026-10-12');assert.equal(await page.getByRole('button',{name:'Week',exact:true}).getAttribute('aria-pressed'),'true');
  assert.ok(await page.evaluate(()=>window.calendarCalls.some(c=>c.name==='get_appointments_with_privacy'&&c.args.p_start_date==='2026-10-12'&&c.args.p_end_date==='2026-10-18')),'Monday/Sunday query matches visible week');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'calendar does not overflow narrow viewport');
  const href=await page.getByRole('link',{name:'Open in new tab'}).getAttribute('href');assert.equal(new URL(href,url).searchParams.get('view'),'my');assert.equal(new URL(href,url).searchParams.get('date'),'2026-10-12');
  // Real native fullscreen and its exit retain date/view state.
  if(viewport.width===1280){await page.getByRole('button',{name:'Full screen calendar',exact:true}).click();await page.waitForFunction(()=>Boolean(document.fullscreenElement));await page.getByRole('button',{name:'Next calendar period'}).click();await page.waitForFunction(()=>document.querySelector('input[aria-label="Calendar date"]').value==='2026-10-19'&&!document.querySelector('[aria-busy="true"]'));assert.ok(await page.evaluate(()=>Boolean(document.fullscreenElement)));await page.getByRole('button',{name:'Previous calendar period'}).click();await page.getByText('Site visit',{exact:true}).waitFor();await page.getByRole('button',{name:'Exit full screen calendar',exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);}
  // Browsers denying fullscreen still support an expanded workspace and Escape.
  await page.evaluate(()=>{Element.prototype.requestFullscreen=async()=>{throw Error('Denied')}});await page.getByRole('button',{name:'Full screen calendar',exact:true}).click();await page.locator('.calendar-expanded').waitFor();assert.ok(await page.locator('.calendar-expanded').evaluate(e=>getComputedStyle(e).position==='fixed'&&e.getBoundingClientRect().width>=innerWidth-20));await page.keyboard.press('Escape');assert.equal(await page.locator('.calendar-expanded').count(),0);
  assert.equal(await page.getByLabel('Calendar date').inputValue(),'2026-10-12');
  if(viewport.width===1280)await page.screenshot({path:'/tmp/mjv-shared-calendar-desktop.png',fullPage:true});if(viewport.width===390)await page.screenshot({path:'/tmp/mjv-shared-calendar-mobile.png',fullPage:true});
  // Empty slot opens the actual creation callback with the precise date and time.
  await page.getByRole('button',{name:'Schedule Wed 14 on 2026-10-14 at 1:00 PM',exact:true}).click();await page.getByRole('dialog',{name:'Create event'}).waitFor();assert.deepEqual(JSON.parse(await page.getByTestId('event-selection').textContent()),{date:'2026-10-14',start:'13:00'});await page.getByRole('button',{name:'Close event'}).click();
  // Day and technician views keep the shared grid and work-order navigation.
  await page.getByRole('button',{name:'Day',exact:true}).click();if(viewport.width===1280){
    const event=page.locator('[draggable="true"]').filter({hasText:'Site visit'}).first(),target=page.getByRole('button',{name:'Schedule Mon 12 on 2026-10-12 at 1:00 PM',exact:true});
    await event.dragTo(target);await page.getByRole('button',{name:'Confirm move',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calendarCalls.filter(c=>c.name.startsWith('reschedule_')).length),0);await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.evaluate(()=>window.calendarCalls.filter(c=>c.name.startsWith('reschedule_')).length),0);
    await event.dragTo(target);await page.getByRole('button',{name:'Confirm move',exact:true}).click();await page.waitForFunction(()=>window.calendarCalls.some(c=>c.name==='reschedule_appointment_secure'));assert.equal(await page.evaluate(()=>window.calendarCalls.find(c=>c.name==='reschedule_appointment_secure').args.p_new_start_time),'13:00');assert.equal(await page.evaluate(()=>window.calendarCalls.find(c=>c.name==='reschedule_appointment_secure').args.p_new_end_time),'13:45');
  }
  assert.equal(await page.getByRole('button',{name:'Delete Busy',exact:true}).count(),0);assert.equal(await page.locator('[draggable="true"]').filter({hasText:'Busy'}).count(),0);assert.equal(await page.locator('[draggable="true"]').filter({hasText:'All-day event'}).count(),0);
  await page.getByRole('button',{name:'WO-100',exact:true}).click();assert.equal(await page.evaluate(()=>window.openedWorkOrder),'wo');await page.getByRole('button',{name:'Site visit',exact:true}).click();await page.getByRole('button',{name:'Close details'}).waitFor();
  await page.getByRole('button',{name:'Tech Calendar',exact:true}).click();await page.locator('[data-calendar-time-grid]').waitFor();await page.getByRole('button',{name:'Schedule Alice on 2026-10-12 at 1:00 PM',exact:true}).click();assert.equal(JSON.parse(await page.getByTestId('event-selection').textContent()).technician,'a');await page.getByRole('button',{name:'Close event'}).click();
  await page.getByRole('button',{name:'Gantt',exact:true}).click();await page.locator('[data-calendar-gantt]').waitFor();await page.evaluate(()=>{window.openedWorkOrder=null});await page.getByRole('button',{name:'WO-100',exact:true}).click();assert.equal(await page.evaluate(()=>window.openedWorkOrder),'wo');await page.getByRole('button',{name:'View Alice on 2026-10-14',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Day',exact:true}).getAttribute('aria-pressed'),'true');await page.getByLabel('Calendar date').fill('2026-10-12');
  // Month and agenda remain available alongside the shared day/week views.
  await page.getByRole('button',{name:'My Calendar',exact:true}).click();await page.getByRole('button',{name:'Month',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-calendar-time-grid]'));await page.getByRole('button',{name:'Agenda',exact:true}).click();await page.getByText('Group by:',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);await page.close();
 }
 for(const viewport of [{width:1280,height:900},{width:390,height:844}]) {
  const page=await browser.newPage({viewport,timezoneId:'America/Los_Angeles'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
  const base='http://127.0.0.1:'+server.address().port;
  await page.goto(base+'/?surface=dispatch');await page.getByLabel('Calendar date').fill('2026-10-12');await page.getByText('Site visit',{exact:true}).waitFor();
  const slot=page.getByRole('button',{name:'Schedule Alice on 2026-10-12 at 1:30 PM',exact:true});await slot.click();assert.deepEqual(JSON.parse(await page.getByTestId('event-selection').textContent()),{date:'2026-10-12',start:'13:30',technician:'a'});await page.getByRole('button',{name:'Close event'}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Dispatch stays inside mobile viewport');
  if(viewport.width===1280){const event=page.locator('[draggable="true"]').filter({hasText:'Site visit'}).first();await event.evaluate(e=>e.scrollIntoView({block:'center'}));await event.dragTo(slot);await page.getByRole('button',{name:'Proceed',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calendarCalls.filter(c=>c.name.startsWith('reschedule_')).length),0);await page.getByRole('button',{name:'Cancel',exact:true}).click();await event.evaluate(e=>e.scrollIntoView({block:'center'}));await event.dragTo(slot);await page.getByRole('button',{name:'Proceed',exact:true}).click();await page.waitForFunction(()=>window.calendarCalls.some(c=>c.name==='reschedule_appointment_secure'));}

  await page.evaluate(()=>{Element.prototype.requestFullscreen=async()=>{throw Error('Denied')}});await page.getByRole('button',{name:'Full screen calendar',exact:true}).click();await page.locator('.calendar-expanded').waitFor();await page.getByRole('button',{name:'Next calendar period'}).click();assert.equal(await page.getByLabel('Calendar date').inputValue(),'2026-10-13');assert.equal(await page.locator('.calendar-expanded').count(),1);for (const view of ['Week','Month','Gantt']) {await page.getByRole('button',{name:view,exact:true}).click();await page.locator(view==='Week'?'[data-calendar-time-grid]':view==='Month'?'[data-calendar-month-grid]':'[data-calendar-gantt]').waitFor();assert.equal(await page.getByLabel('Calendar date').inputValue(),'2026-10-13');assert.equal(await page.locator('.calendar-expanded').count(),1);}
  await page.getByRole('button',{name:'Day',exact:true}).click();await page.getByRole('button',{name:'Schedule Alice on 2026-10-13 at 1:30 PM',exact:true}).waitFor();assert.equal(await page.locator('.calendar-expanded').count(),1);await page.getByRole('button',{name:'Exit full screen calendar',exact:true}).click();
  await page.goto(base+'/?surface=appointment');await page.getByLabel('Appointment start time').waitFor();assert.equal(await page.getByLabel('Appointment start time').inputValue(),'09:20');assert.equal(await page.getByLabel('Appointment end time').inputValue(),'10:20');await page.getByRole('button',{name:'Shop Time',exact:true}).click();await page.getByLabel('Appointment end time').fill('10:45');await page.getByRole('button',{name:'Schedule Appointment',exact:true}).click();await page.waitForFunction(()=>window.appointmentSaved===true);assert.equal(await page.evaluate(()=>window.calendarWrites[0].value.assigned_technician),'a');assert.equal(await page.evaluate(()=>window.calendarWrites[0].value.start_time),'09:20');assert.equal(await page.evaluate(()=>window.calendarWrites[0].value.end_time),'10:45');
  assert.deepEqual(errors,[]);await page.close();
 }
 const delayed=await browser.newPage();await delayed.goto('http://127.0.0.1:'+server.address().port+'/calendar?popup=true&view=my&viewMode=day&date=2026-10-12&delayAuth=true');await delayed.getByRole('button',{name:'Site visit',exact:true}).waitFor();assert.equal(await delayed.getByLabel('Calendar date').inputValue(),'2026-10-12');await delayed.close();
 console.log('My/technician calendar day/week, Monday range, reminders, all-day events, creation, work-order links, month/agenda, native/fallback fullscreen and tab state passed at desktop and mobile widths.');
} finally {await browser?.close();await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}
