import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const vault=ts.transpileModule(await readFile(new URL('../../supabase/functions/_shared/security-payment-vault.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const vaultUrl='data:text/javascript;base64,'+Buffer.from(vault).toString('base64');
const source=(await readFile(new URL('../../supabase/functions/_shared/security-charge.ts',import.meta.url),'utf8')).replace("'./security-payment-vault.ts'",JSON.stringify(vaultUrl));
const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {securityCharge,classifySecurityCharge}=await import('data:text/javascript;base64,'+Buffer.from(output).toString('base64'));
const requests=[];
const fake=(raw,status=200)=>async(url,init)=>{requests.push({url,init});return new Response(JSON.stringify(raw),{status});};
const charge=(type,fetcher,id)=>securityCharge('sandbox','server-token',type,'vault-method',35,'request-id','Monitoring','SETTLED',id,fetcher);
assert.equal((await charge('card',fake({id:'charge-1',status:'CAPTURED',amount:'35.00'}))).state,'paid');
assert.equal(JSON.parse(requests[0].init.body).cardOnFile,'vault-method');assert.equal(requests[0].init.headers['Request-Id'],'request-id');
assert.equal((await charge('ach',fake({id:'ach-1',status:'PENDING',amount:'35.00'}))).state,'pending');
assert.equal(JSON.parse(requests[1].init.body).paymentMode,'WEB');
assert.equal((await charge('ach',fake({id:'ach-1',status:'SETTLED',amount:'35.00'}),'ach-1')).state,'paid');assert.equal(requests[2].init.method,'GET');assert.equal(requests[2].init.body,undefined);
assert.equal(classifySecurityCharge({id:'ach-1',status:'PENDING'},'ach','').state,'pending');
assert.equal(classifySecurityCharge({id:'ach-1',status:'PENDING'},'ach','PENDING').state,'pending','Misconfiguration cannot mark pending ACH as settled');
assert.equal(classifySecurityCharge({id:'ach-1',status:'DECLINED'},'ach','DECLINED').state,'declined');
assert.equal((await charge('card',fake({id:'charge-2',status:'DECLINED',amount:'35.00'}))).state,'declined');
assert.equal((await charge('card',fake({id:'charge-3',status:'CAPTURED',amount:'350.00'}))).state,'unknown');
assert.equal((await charge('card',fake({id:'wrong',status:'CAPTURED',amount:'35.00'}),'expected')).state,'unknown');
assert.equal((await charge('card',fake({},503))).state,'unknown');
let attempts=0;assert.equal((await charge('card',async()=>{attempts++;throw new Error('timeout');})).state,'unknown');assert.equal(attempts,1,'An uncertain POST is never automatically retried');
console.log('Charge tests passed: exact amount, saved methods, card/ACH settlement, pending/declined, read-only reconciliation, unknown outcomes without replay.');
