import {PGlite} from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const db=new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA private;
CREATE TABLE invoices(id int PRIMARY KEY,total numeric,amount_paid numeric);
CREATE TABLE payments(invoice_id int,amount numeric);
CREATE TABLE commission_records(invoice_id int,amount_collected numeric,amount_earned numeric,total_potential_commission numeric,status text,updated_at timestamptz);
INSERT INTO invoices VALUES(1,100,0),(2,200,0);INSERT INTO commission_records VALUES(1,0,0,10,'pending',now()),(2,0,0,20,'pending',now());
CREATE FUNCTION update_commission_on_payment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM id FROM invoices WHERE id=NEW.invoice_id; RETURN NEW; END $$;
CREATE TRIGGER trigger_update_commission_on_invoice_update AFTER UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_commission_on_payment();
CREATE FUNCTION record_payment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE invoices SET amount_paid=amount_paid+NEW.amount WHERE id=NEW.invoice_id; RETURN NEW; END $$;
CREATE TRIGGER payment_balance AFTER INSERT ON payments FOR EACH ROW EXECUTE FUNCTION record_payment();`);
await assert.rejects(db.exec('INSERT INTO payments VALUES(1,25)'),/no field "invoice_id"/,'Reproduces the hosted failure');
await db.exec(await readFile(new URL('../../supabase/migrations/20261002172125_fix_commission_invoice_payment_trigger.sql',import.meta.url),'utf8'));
await db.exec('INSERT INTO payments VALUES(1,25)');
let rows=(await db.query('select invoice_id,amount_collected,amount_earned,status from commission_records order by invoice_id')).rows;
assert.equal(rows[0].invoice_id,1);assert.equal(Number(rows[0].amount_collected),25);assert.equal(Number(rows[0].amount_earned),2.5);assert.equal(rows[0].status,'accruing');assert.equal(rows[1].status,'pending');
await db.exec('INSERT INTO payments VALUES(1,75)');assert.equal((await db.query('select status from commission_records where invoice_id=1')).rows[0].status,'ready_to_pay');
await db.exec('UPDATE invoices SET amount_paid=0 WHERE id=1');assert.equal((await db.query('select status from commission_records where invoice_id=1')).rows[0].status,'pending');
await db.close();console.log('Invoice commission tests passed: hosted trigger failure reproduced, partial/full payment tracking, unrelated invoices, and reversed balances.');
