import { PGlite } from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const db = new PGlite();
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const customer=id(1), otherCustomer=id(2), contact=id(3), otherContact=id(4), contract=id(5), otherContract=id(6), token=id(7), otherToken=id(8), org=id(9), template=id(10);
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth;
GRANT USAGE ON SCHEMA auth,public TO anon,authenticated;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE contacts(id uuid PRIMARY KEY,organization_id uuid,portal_user_id uuid,full_name text,email text,phone text,street_address text,city text,state text,zip_code text);
CREATE TABLE profiles(id uuid PRIMARY KEY,contact_id uuid,organization_id uuid,role text);
CREATE TABLE organizations(id uuid PRIMARY KEY); INSERT INTO organizations VALUES('${org}');
CREATE TABLE quickbooks_settings(id uuid); CREATE TABLE qbo_oauth_sessions(id uuid);
CREATE TABLE security_contract_templates(id uuid PRIMARY KEY,organization_id uuid,name text,contract_terms text);
CREATE TABLE security_contracts(id uuid PRIMARY KEY,contact_id uuid,organization_id uuid,template_id uuid,contract_number text,status text,magic_link_token uuid,magic_link_expires_at timestamptz,monthly_price numeric,term_months int,renewal_term_months int,cancellation_notice_days int,customer_completed_at timestamptz,customer_signature text,customer_signature_date timestamptz,payment_method text CHECK(payment_method IN ('credit_card','ach')),agreement_type text DEFAULT 'monitoring',billing_frequency_override text,updated_at timestamptz,created_at timestamptz DEFAULT now());
CREATE TABLE company_settings(organization_id uuid,company_name text,company_email text,annual_billing_enabled boolean,default_billing_preference text,annual_discount_type text,annual_discount_percentage numeric,annual_discount_flat_amount numeric);
CREATE TABLE monitoring_services(id uuid PRIMARY KEY,name text);
CREATE TABLE security_contract_services(id uuid PRIMARY KEY,contract_id uuid,service_id uuid,monthly_price numeric);
CREATE TABLE security_contract_emergency_contacts(contract_id uuid,organization_id uuid,contact_name text,phone_number text,password_codeword text,can_authorize_entry boolean,priority_order int);
CREATE TABLE onboarding_progress(contract_id uuid); CREATE TABLE security_contract_fields(id uuid);
ALTER TABLE security_contracts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anonymous users can view contracts via magic link" ON security_contracts FOR SELECT TO anon USING(magic_link_token IS NOT NULL AND magic_link_expires_at>now());
CREATE POLICY "Anonymous users can update contracts via magic link" ON security_contracts FOR UPDATE TO anon USING(magic_link_token IS NOT NULL AND magic_link_expires_at>now());
GRANT SELECT,UPDATE ON security_contracts TO anon;
INSERT INTO contacts VALUES('${contact}','${org}','${customer}','Customer','c@example.com','5551231234','1 Main St','Topeka','KS','66604'),('${otherContact}','${org}','${otherCustomer}','Other','o@example.com','5551231234','2 Main','Topeka','KS','66604');
INSERT INTO profiles VALUES('${customer}','${contact}','${org}','portal'),('${otherCustomer}','${otherContact}','${org}','portal'),('${id(11)}',null,'${org}','admin'),('${id(12)}',null,'${org}','finance');
INSERT INTO security_contract_templates VALUES('${template}','${org}','Monitoring','Original terms [term].');
INSERT INTO company_settings VALUES('${org}','Electronic Life','support@example.com',false,'monthly','percentage',0,0);
INSERT INTO security_contracts(id,contact_id,organization_id,template_id,contract_number,status,magic_link_token,magic_link_expires_at,monthly_price,term_months,renewal_term_months,cancellation_notice_days)
VALUES('${contract}','${contact}','${org}','${template}','SC-1','pending_customer','${token}',now()+interval '1 day',35,36,1,30),('${otherContract}','${otherContact}','${org}','${template}','SC-2','pending_customer','${otherToken}',now()+interval '1 day',40,36,1,30);
`);
const migration = await readFile(new URL('../../supabase/migrations/20260930130305_portal_security_onboarding.sql',import.meta.url),'utf8');
await db.exec(migration);
await db.exec(`INSERT INTO security_payment_methods(id,organization_id,contact_id,qbo_customer_id,qbo_method_id,payment_type,display_brand,display_last4,verified_at)
VALUES('${id(13)}','${org}','${contact}','qb-customer','qb-bank','ach','Bank','1234',now()),('${id(14)}','${org}','${otherContact}','other-qb','other-bank','ach','Bank','9876',now());`);
async function role(name, user='') { await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}'; SET ROLE ${name}`); }
async function rpc(action,cid=null,tok=null,payload={}) {
 return (await db.query('select public.portal_security_onboarding($1,$2,$3,$4) as result',[action,cid,tok,JSON.stringify(payload)])).rows[0].result;
}
await role('anon');
await assert.rejects(rpc('list'));
await assert.rejects(rpc('get',contract,id(999)));
await assert.rejects(rpc('get',otherContract,token),'A token cannot authorize another agreement');
assert.equal((await db.query('select count(*) from security_contracts')).rows[0].count,0,'Unfiltered anonymous table reads are denied');
await assert.rejects(db.exec("select * from security_onboarding_drafts"),'Draft table cannot be read directly');
let loaded=await rpc('get',null,token);
assert.equal(loaded.id,contract); assert.equal(loaded.document.contract_number,'SC-1');
assert.equal(loaded.magic_link_token,undefined); assert.equal(loaded.contact.portal_user_id,undefined);
const form={personalInfo:{full_name:'Customer Signed',email:'c@example.com',phone:'5551231234'},propertyInfo:{address_line1:'1 Main St',city:'Topeka',state:'KS',zip_code:'66604'},emergencyContacts:[{name:'First',phone:'5551111111',password:'secret-one',canAuthorize:true},{name:'Second',phone:'5552222222',password:'secret-two',canAuthorize:false}],paymentMethod:'ach',paymentMethodId:id(13),billingPreference:'monthly',paymentDetails:{cardNumber:'4111111111111111',cvv:'123',accountNumber:'123456789'},signature:'do not save'};
let saved=await rpc('save',contract,token,{revision:0,current_step:4,form_data:form});
assert.equal(saved.revision,1);
loaded=await rpc('get',null,token); assert.equal(loaded.draft.current_step,4);
assert.equal(loaded.draft.form_data.personalInfo.full_name,'Customer Signed');
assert.equal(loaded.draft.form_data.paymentDetails,undefined); assert.equal(loaded.draft.form_data.signature,undefined);
assert.equal(JSON.stringify(loaded.draft).includes('4111111111111111'),false);
await assert.rejects(rpc('save',contract,token,{revision:0,current_step:2,form_data:form}),'A second device cannot overwrite a newer revision');
await assert.rejects(rpc('save',contract,token,{revision:1,current_step:7,form_data:form}),'Invalid steps rejected');
await role('authenticated',otherCustomer); assert.equal((await rpc('list')).length,1);
await assert.rejects(rpc('get',contract));
await role('authenticated',customer); assert.equal((await rpc('list'))[0].id,contract);
assert.equal((await rpc('get',contract)).draft.current_step,4);
await role('postgres'); await db.exec(`update security_contracts set magic_link_expires_at=now()-interval '1 day' where id='${contract}'`);
await role('anon'); await assert.rejects(rpc('get',null,token),'Expired links cannot load the draft');
await role('authenticated',customer); loaded=await rpc('get',contract);
assert.equal(loaded.draft.revision,1,'Portal owner can resume after invitation expiry');
const payload={revision:1,form_data:form,signature:'data:image/png;base64,aGVsbG8=',accepted:true,autopay_accepted:true,document_version:loaded.document_version};
await assert.rejects(rpc('submit',contract,null,{...payload,accepted:false}));
await assert.rejects(rpc('submit',contract,null,{...payload,autopay_accepted:false}),'AutoPay consent is required');
await assert.rejects(rpc('submit',contract,null,{...payload,form_data:{...form,paymentMethodId:''}}),'Preference alone cannot replace a payment method');
await assert.rejects(rpc('submit',contract,null,{...payload,form_data:{...form,paymentMethodId:id(14)}}),'Another customer method cannot be selected');
await role('postgres');
await db.exec(`update security_payment_methods set verified_at=now()-interval '10 minutes' where id='${id(13)}'`);
await role('authenticated',customer);
await assert.rejects(rpc('submit',contract,null,payload),'Payment availability must be reverified at signing');
await role('postgres');await db.exec(`update security_payment_methods set verified_at=now() where id='${id(13)}'`);
await role('authenticated',customer);
await assert.rejects(rpc('submit',contract,null,{...payload,form_data:{...form,billingPreference:'annual'}}));
await role('postgres'); await db.exec(`update security_contract_templates set contract_terms='Updated terms [term].' where id='${template}'`);
await role('authenticated',customer);
await assert.rejects(rpc('submit',contract,null,payload),'Changed terms require review before acceptance');
loaded=await rpc('get',contract); payload.document_version=loaded.document_version;
await rpc('submit',contract,null,payload);
loaded=await rpc('get',contract);
assert.equal(loaded.status,'pending_approval'); assert.equal(loaded.draft,null);
assert.equal(loaded.signed_snapshot_available,true);
assert.equal(loaded.document.personalInfo.full_name,'Customer Signed');
assert.equal(JSON.stringify(loaded.document).includes('secret-one'),false,'Monitoring codewords are excluded from agreement copies');
await assert.rejects(rpc('submit',contract,null,payload),'Repeated signing cannot duplicate acceptance');
await assert.rejects(rpc('save',contract,null,{revision:1,current_step:1,form_data:form}),'Submitted agreements cannot be edited by stale tabs');
await role('postgres');
assert.equal((await db.query('select count(*) from security_contract_emergency_contacts')).rows[0].count,2);
await db.exec(`update security_contract_templates set contract_terms='Future template' where id='${template}'; update security_contracts set monthly_price=99,status='active' where id='${contract}'`);
await role('authenticated',customer); loaded=await rpc('get',contract);
assert.equal(loaded.document.monthly_price,35,'Signed price remains immutable in the accepted snapshot');
assert.equal(loaded.document.template.contract_terms,'Updated terms [term].');
await role('anon'); await assert.rejects(rpc('save',otherContract,token,{revision:0,current_step:1,form_data:form}));
await assert.rejects(db.exec('select * from security_payment_methods'),'Anonymous customers cannot read the payment vault table');
// Exercise the Admin exception under the same trigger used by direct staff updates.
await role('postgres');await db.exec('GRANT SELECT,UPDATE ON security_contracts TO authenticated; CREATE POLICY staff_fixture ON security_contracts TO authenticated USING (true) WITH CHECK (true)');
await role('authenticated',id(12));
await assert.rejects(db.exec(`update security_contracts set security_billing_mode='mail' where id='${otherContract}'`),'Finance cannot grant mailed billing');
await role('authenticated',otherCustomer);
await assert.rejects(db.exec(`update security_contracts set security_billing_mode='mail' where id='${otherContract}'`),'Portal customers cannot grant mailed billing');
await role('authenticated',id(11));
await db.exec(`update security_contracts set security_billing_mode='mail' where id='${otherContract}'`);
let row=(await db.query(`select monthly_price,mail_invoice_fee,mail_billing_authorized_by from security_contracts where id='${otherContract}'`)).rows[0];
assert.equal(Number(row.monthly_price),47);assert.equal(Number(row.mail_invoice_fee),7);assert.equal(row.mail_billing_authorized_by,id(11));
await db.exec(`update security_contracts set mail_invoice_fee=0 where id='${otherContract}'`);
assert.equal(Number((await db.query(`select mail_invoice_fee from security_contracts where id='${otherContract}'`)).rows[0].mail_invoice_fee),7,'Fee cannot be overridden');
await db.exec(`update security_contracts set security_billing_mode='autopay' where id='${otherContract}'`);
assert.equal(Number((await db.query(`select monthly_price from security_contracts where id='${otherContract}'`)).rows[0].monthly_price),40,'Requiring AutoPay removes the fee exactly once');
await assert.rejects(db.exec(`update security_contracts set status='active' where id='${otherContract}'`),'Staff cannot activate an account without payment and consent');
await db.exec(`update security_contracts set security_billing_mode='mail' where id='${otherContract}'`);
await role('anon');loaded=await rpc('get',otherContract,otherToken);
await rpc('submit',otherContract,otherToken,{revision:0,form_data:{...form,paymentMethodId:'',paymentMethod:''},signature:payload.signature,accepted:true,document_version:loaded.document_version});
loaded=await rpc('get',otherContract,otherToken);
assert.equal(loaded.document.billing_mode,'mail');assert.equal(loaded.document.monthly_price,47);assert.equal(loaded.document.mail_invoice_fee,7);assert.equal(loaded.document.autopay_authorization,null);
await role('authenticated',id(11));
await assert.rejects(db.exec(`update security_contracts set security_billing_mode='autopay' where id='${otherContract}'`),'Accepted billing terms cannot silently change');
await role('postgres');
await db.exec(`
ALTER TABLE contacts ADD COLUMN tax_environment text;
ALTER TABLE security_contracts ADD COLUMN activated_at timestamptz;
ALTER TABLE security_contracts ADD COLUMN subscription_id uuid;
CREATE TABLE legacy_subscription_calls(value integer);
INSERT INTO legacy_subscription_calls VALUES(0);
CREATE FUNCTION public.create_subscription_from_contract() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE public.legacy_subscription_calls SET value=value+1; RETURN NEW; END $$;
CREATE TRIGGER trigger_create_subscription_from_contract BEFORE UPDATE ON security_contracts FOR EACH ROW WHEN(NEW.status='active' AND OLD.status IS DISTINCT FROM 'active') EXECUTE FUNCTION public.create_subscription_from_contract();
CREATE TABLE tax_classifications(id uuid PRIMARY KEY,organization_id uuid,is_active boolean,label text);
INSERT INTO tax_classifications VALUES('${id(20)}','${org}',true,'Monitoring');
CREATE TABLE department_modules(organization_id uuid,module_key text,is_active boolean);
INSERT INTO department_modules VALUES('${org}','contract_management',true);
CREATE TABLE invoices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid,organization_id uuid,contact_id uuid,invoice_number text,invoice_date date,due_date date,invoice_type text,source_type text,status text,subtotal numeric,total numeric,amount_due numeric,billing_name text,billing_address_line1 text,billing_city text,billing_state text,billing_zip text,jobsite_address text,jobsite_city text,jobsite_state text,jobsite_zip text,tax_environment text,tax_project_type text,notes text);
CREATE TABLE invoice_line_items(id uuid DEFAULT gen_random_uuid(),invoice_id uuid,organization_id uuid,description text,quantity numeric,unit_price numeric,amount numeric,sort_order int,item_type text,is_taxable boolean,tax_classification_id uuid);
CREATE TABLE payments(created_at timestamptz DEFAULT now(),id uuid DEFAULT gen_random_uuid(),company_id uuid,organization_id uuid,invoice_id uuid,amount numeric,payment_method text,payment_processor text,processor_transaction_id text,reference_number text,notes text,qbo_payment_id text,synced_at timestamptz);
CREATE FUNCTION calculate_tax_context(text,uuid) RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object('tax_calculation_status',coalesce(current_setting('test.tax_status',true),'ready')) $$;
CREATE FUNCTION submit_invoice(p_id uuid) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN UPDATE public.invoices SET status='submitted',invoice_number='INV-TEST' WHERE id=p_id; RETURN '{"success":true}'::jsonb; END $$;
`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260930140901_security_recurring_autopay.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../../supabase/migrations/20260930142857_security_portal_contract_summary.sql',import.meta.url),'utf8'));
assert.equal((await db.query("select private.security_period_date('2024-01-31',1,1)::text as value")).rows[0].value,'2024-02-29');
await db.exec(`update security_contracts set status='approved',monitoring_tax_classification_id='${id(20)}' where id='${contract}'; update security_contracts set status='active',activated_at=now() where id='${contract}'`);
assert.equal((await db.query('select value from legacy_subscription_calls')).rows[0].value,0,'Portal billing cannot create a second legacy subscription');
async function billing(action,cycle=null,payload={}) { return (await db.query('select public.security_recurring_billing($1,$2,$3) as result',[action,cycle?.id||null,JSON.stringify({...payload,lease_token:cycle?.lease_token})])).rows[0].result; }
await role('authenticated',customer);await assert.rejects(billing('generate'));
assert.equal((await db.query('select security_portal_enabled() as value')).rows[0].value,true);
loaded=await rpc('get',contract);assert.equal(loaded.summary.months_remaining,36);assert.equal(loaded.summary.monthly_price,35);
await role('postgres');await db.exec(`update company_settings set portal_security_contracts_enabled=false`);
await role('authenticated',customer);assert.equal((await rpc('list')).length,0);await assert.rejects(rpc('get',contract));
await role('anon');assert.equal((await rpc('get',otherContract,otherToken)).summary,null,'Valid invitation retains access to agreement when portal section is hidden');
await role('postgres');await db.exec('update company_settings set portal_security_contracts_enabled=true');
assert.equal((await billing('generate')).generated,1);assert.equal((await billing('generate')).generated,0,'A period is invoiced only once');
let cycle=await billing('lease');assert.equal(cycle.state,'preparing');assert.equal(await billing('lease'),null,'Work cannot be leased twice');
await billing('prepare',cycle);cycle=await billing('lease');assert.equal(cycle.state,'notice');
await billing('notice',cycle);assert.equal(await billing('lease'),null,'Advance notice prevents immediate charging');
await db.exec("update security_billing_cycles set debit_after=now()-interval '1 second',notice_sent_at=now()-interval '11 days'");
cycle=await billing('lease');const claimed=await billing('charge',cycle);assert.equal(claimed.cycle.state,'processing');
await billing('result',cycle,{state:'pending',processor_id:'qb-payment-1',processor_status:'PENDING'});
assert.equal((await db.query('select count(*) from payments')).rows[0].count,0,'ACH submission does not mean payment received');
await db.exec('update security_billing_cycles set next_check_at=now()');cycle=await billing('lease');
await billing('result',cycle,{state:'paid',processor_id:'qb-payment-1',processor_status:'SETTLED'});
assert.equal((await db.query('select count(*) from payments')).rows[0].count,1);
await assert.rejects(billing('result',cycle,{state:'paid',processor_id:'qb-payment-1'}),'Payment replay rejected');
await db.exec(`insert into payments(invoice_id,qbo_payment_id,reference_number,amount) values('${cycle.invoice_id}','qb-accounting-1','qb-payment-1',35)`);
assert.equal((await db.query('select count(*) from payments')).rows[0].count,1,'Accounting webhook cannot duplicate the recorded charge');
await role('authenticated',customer);await rpc('revoke_autopay',contract);loaded=await rpc('get',contract);assert.equal(loaded.summary.autopay_paused,true);
await role('postgres');
await db.exec(`update security_billing_cycles set state='ready',notice_sent_at=now()-interval '11 days',debit_after=now()-interval '1 day',accounting_synced_at=now(),next_check_at=now() where id='${cycle.id}'`);
cycle=await billing('lease');assert.equal(await billing('charge',cycle),null,'Revoked AutoPay never initiates another charge');
assert.equal((await db.query('select state from security_billing_cycles where id=$1',[cycle.id])).rows[0].state,'cancelled');
await db.exec(`update security_contracts set monitoring_tax_classification_id='${id(20)}',status='active',activated_at=now() where id='${otherContract}'`);
assert.equal((await billing('generate')).generated,1);cycle=await billing('lease');
await db.exec("set test.tax_status='review_required'");await billing('prepare',cycle);
assert.equal((await db.query('select state from security_billing_cycles where id=$1',[cycle.id])).rows[0].state,'review','Unresolved tax prevents invoicing and debit');
await role('authenticated',id(12));await assert.rejects(db.query("select public.security_billing_review('retry_confirmed_no_charge',$1,'Tax settings reviewed',null)",[cycle.id]),'Finance cannot authorize billing retries');
await role('authenticated',id(11));await db.query("select public.security_billing_review('retry_confirmed_no_charge',$1,'Tax settings reviewed with merchant',null)",[cycle.id]);
await role('postgres');await db.exec("set test.tax_status='ready'");cycle=await billing('lease');await billing('prepare',cycle);
assert.equal((await db.query('select state from security_billing_cycles where id=$1',[cycle.id])).rows[0].state,'mail','Admin mail exception is invoiced without a debit');
assert.equal((await db.query('select count(*) from security_billing_reviews')).rows[0].count,1);

await role('postgres');await assert.rejects(db.exec(`update security_contracts set autopay_paused=false where id='${contract}'`),'Revocation requires new authorization');
await role('postgres');
await db.exec(`ALTER TABLE security_contract_templates ALTER COLUMN id SET DEFAULT gen_random_uuid(); ALTER TABLE security_contract_templates ADD COLUMN description text; ALTER TABLE security_contract_templates ADD COLUMN is_active boolean DEFAULT true; ALTER TABLE security_contract_templates ADD COLUMN requires_approval boolean; ALTER TABLE security_contract_templates ADD COLUMN approval_role text; ALTER TABLE security_contract_templates ADD COLUMN auto_create_subscription boolean; ALTER TABLE security_contract_templates ADD COLUMN default_billing_plan_id uuid;
INSERT INTO organizations VALUES('b324e4e3-cd2e-4c68-8df8-3e27c7e08f15');
INSERT INTO security_contract_templates(id,organization_id,name,contract_terms) VALUES('1546a013-6a30-4aed-b58a-70dd74a6ec25','b324e4e3-cd2e-4c68-8df8-3e27c7e08f15','Original EL template','1. Term & Renewal\nOld multi-year renewal surcharge.\n2. Billing, Early Cancellation & Service Suspension\nOld formula.\n3. Automatic Payments\nOld payment clause.\n4. Rate Adjustments (NEW)\nOriginal rate policy.\n16. Legal Action & Liquidated Damages\nConflicting formula.\n17. Insurance Requirements\nOriginal insurance clause.');`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260930175017_security_monitoring_terms_review.sql',import.meta.url),'utf8'));
const revised=(await db.query("select * from security_contract_templates where name like '%DRAFT LEGAL REVIEW%'")).rows[0];
assert.equal(revised.is_active,false);assert.equal(revised.auto_create_subscription,false);
assert.ok(revised.contract_terms.includes('initial monitoring term is 36 months'));assert.ok(revised.contract_terms.includes('continues automatically from month to month'));
assert.ok(!revised.contract_terms.includes('Old multi-year renewal surcharge'));
assert.ok((await db.query("select contract_terms from security_contract_templates where id='1546a013-6a30-4aed-b58a-70dd74a6ec25'")).rows[0].contract_terms.includes('Old multi-year renewal surcharge'),'Original template remains intact');
await assert.rejects(db.query('update security_contract_templates set is_active=true where id=$1',[revised.id]),'Unfinished legal draft cannot be activated');
const { testStaff } = await import('./staff.mjs');
await testStaff(db,{id,org,contact,otherContact,template,form,role,rpc});
await db.close();
console.log('Security onboarding database tests passed: ownership, expiry, safe drafts, revisions, atomic signing, immutable copy, required verified AutoPay, Admin-only mail billing/$7 fee, portal visibility/summary, recurring billing idempotency, advance notices, pending/settled payments, webhook deduplication, tax blocking, and revocation.');
