import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';
const source=await readFile(new URL('../../supabase/functions/_shared/security-payment-vault.ts',import.meta.url),'utf8');
const {outputText}=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}});
const {paymentsOrigin,maskedPayment,vaultRequest}=await import('data:text/javascript;base64,'+Buffer.from(outputText).toString('base64'));
assert.equal(paymentsOrigin('production'),'https://api.intuit.com');
assert.equal(paymentsOrigin('sandbox'),'https://sandbox.api.intuit.com');
const card=maskedPayment({id:'card-1',number:'xxxxxxxxxxxx4321',cardType:'Visa',expMonth:'12',expYear:'2030',cvc:'123'},'card');
assert.equal(card.display_last4,'4321');assert.equal(card.exp_year,2030);assert.equal(card.cvc,undefined);assert.equal(card.number,undefined);
const bank=maskedPayment({id:'bank-1',accountNumber:'xxxxx6789',bankName:'Test Bank',routingNumber:'123456789'},'ach');
assert.equal(bank.display_last4,'6789');assert.equal(bank.routingNumber,undefined);
const requests=[];
const fake=async(url,init)=>{requests.push({url,init});return new Response(JSON.stringify({id:'saved'}),{status:200,headers:{'Content-Type':'application/json'}});};
await vaultRequest(paymentsOrigin('sandbox'),'server-token','customer/1','card','short-lived-token',undefined,fake);
assert.ok(requests[0].url.endsWith('/customers/customer%2F1/cards/createFromToken'));
assert.deepEqual(JSON.parse(requests[0].init.body),{value:'short-lived-token'});
await vaultRequest(paymentsOrigin('sandbox'),'server-token','customer/1','ach',undefined,'bank/1',fake);
assert.ok(requests[1].url.endsWith('/customers/customer%2F1/bank-accounts/bank%2F1'));
assert.equal(requests[1].init.method,'GET');
await assert.rejects(vaultRequest(paymentsOrigin('sandbox'),'server-token','c','card',undefined,undefined,async()=>new Response('raw processor message with card number',{status:403})),/Payments access is unavailable/);
console.log('Payment vault tests passed: Intuit endpoints, token-only requests, masked data, safe errors.');
