import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
import {webcrypto} from 'node:crypto';
if(!globalThis.crypto) globalThis.crypto=webcrypto;
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const load=s=>import('data:text/javascript;base64,'+Buffer.from(compile(s)).toString('base64'));
const {ensureSecurityQboCustomer}=await load(await readFile(new URL('../../supabase/functions/_shared/security-qbo-customer.ts',import.meta.url),'utf8'));
const connection={id:'conn',organization_id:'org',realm_id:'realm',environment:'sandbox'};
let contact={contact_name:'Test Customer',email:'test@example.com'},matches=[],saved=false,failSave=false,providerFail=false,requests=[];
const admin={from(table){const filters={};let payload;const result=()=>table==='contacts'?(payload?{error:failSave?{message:'failure'}:null}:{data:contact}):{data:null};const q={select:()=>q,eq:(k,v)=>{filters[k]=v;return q},maybeSingle:async()=>{assert.equal(filters.organization_id,'org');return result()},update:p=>{payload=p;saved=p;return q},then:done=>Promise.resolve(result()).then(done)};return q;}};
const request=async(_,conn,method,path,body)=>{requests.push({conn,method,path,body});return method==='GET'?{ok:!providerFail,data:{QueryResponse:{Customer:matches}}}:{ok:!providerFail,data:{Customer:{Id:'new-customer'}}};};
assert.equal(await ensureSecurityQboCustomer(admin,connection,'contact',request),'new-customer');assert.equal(saved.qbo_customer_id,'new-customer');
assert.equal(requests.filter(r=>r.method==='POST').length,1);const key=requests.find(r=>r.method==='POST').path;
requests=[];failSave=true;await assert.rejects(ensureSecurityQboCustomer(admin,connection,'contact',request),/link could not be saved/);failSave=false;
assert.equal(requests.find(r=>r.method==='POST').path,key,'Retries use the same provider request ID');
matches=[{Id:'existing',PrimaryEmailAddr:{Address:'TEST@example.com'},Active:true}];requests=[];
assert.equal(await ensureSecurityQboCustomer(admin,connection,'contact',request),'existing');assert.equal(requests.some(r=>r.method==='POST'),false);
matches[0].PrimaryEmailAddr.Address='other@example.com';await assert.rejects(ensureSecurityQboCustomer(admin,connection,'contact',request),/review an existing/);
matches[0].PrimaryEmailAddr.Address='test@example.com';matches[0].Active=false;await assert.rejects(ensureSecurityQboCustomer(admin,connection,'contact',request),/review an existing/);
matches=[];providerFail=true;await assert.rejects(ensureSecurityQboCustomer(admin,connection,'contact',request),/unavailable/);providerFail=false;
contact={qbo_customer_id:'linked'};requests=[];assert.equal(await ensureSecurityQboCustomer(admin,connection,'contact',request),'linked');assert.equal(requests.length,0);
// Admin-only, server-validated catalog setup. No invoices, debits or caller-supplied organization.
let role='admin',active=true,reads=0,writes=0,item={Id:'12',Name:'Monitoring',Type:'Service',Active:true,IncomeAccountRef:{value:'7',name:'Monitoring income'}},saveFail=false;
const setupAdmin={from(){let filters={};const q={update:()=>{writes++;return q},eq:(k,v)=>{filters[k]=v;return q},select:()=>q,maybeSingle:async()=>{assert.equal(filters.organization_id,'org');assert.equal(filters.realm_id,'realm');assert.equal(filters.environment,'sandbox');return {data:saveFail?null:{id:'conn'}}}};return q;}};
globalThis.__setup={createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'staff'}}})},from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{organization_id:'org',role,is_active:active}})})}),corsHeaders:{},getSupabaseAdmin:()=>setupAdmin,getConnection:async()=>connection,qboRequest:async(_,conn,method,path)=>{reads++;assert.equal(method,'GET');return {ok:true,data:path.startsWith('query')?{QueryResponse:{Item:[item]}}:{Item:item}}}};
const source=(await readFile(new URL('../../supabase/functions/security-qbo-billing-setup/index.ts',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
await load(`const {createClient,corsHeaders,getSupabaseAdmin,getConnection,qboRequest}=globalThis.__setup;const Deno={env:{get:()=>''},serve:h=>globalThis.__setupHandler=h};${source}`);
const call=async input=>{const r=await globalThis.__setupHandler(new Request('https://fixture',{method:'POST',body:JSON.stringify(input)}));return {status:r.status,body:await r.json()}};
role='portal';assert.equal((await call({action:'list'})).status,403);assert.equal(reads,0);
role='admin';active=false;assert.equal((await call({action:'save',itemId:'12'})).status,403);assert.equal(writes,0);active=true;
assert.deepEqual((await call({action:'list'})).body.items,[{id:'12',name:'Monitoring',income_account:'Monitoring income'}]);
assert.equal((await call({action:'save',itemId:'12',organization_id:'other'})).status,400);
assert.equal((await call({action:'save',itemId:'12'})).body.success,true);
item.Type='Inventory';const before=writes;assert.equal((await call({action:'save',itemId:'12'})).status,400);assert.equal(writes,before);
item.Type='Service';saveFail=true;assert.equal((await call({action:'save',itemId:'12'})).status,400);
delete globalThis.__setup;delete globalThis.__setupHandler;
console.log('QuickBooks setup tests passed: customer identity, stable retries, scoped persistence, Admin-only catalog and verified income item.');
