import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
export async function testStaff(db, {id,org,contact,otherContact,template,form,role,rpc}) {
 await role('postgres');
 await db.exec(`
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT '{}'::jsonb $$;
 ALTER TABLE profiles ADD COLUMN primary_office_id uuid; ALTER TABLE profiles ADD COLUMN default_office_id uuid;
 CREATE TABLE company_offices(id uuid PRIMARY KEY,organization_id uuid,is_active boolean,is_headquarters boolean,display_order integer);
 INSERT INTO company_offices VALUES('${id(90)}','${org}',true,true,0);
 ALTER TABLE profiles ADD COLUMN is_active boolean DEFAULT true; ALTER TABLE profiles ADD COLUMN can_edit_contacts boolean DEFAULT false;
 ALTER TABLE department_modules ADD COLUMN id uuid DEFAULT gen_random_uuid();
 CREATE FUNCTION public.get_user_module_access(uuid,uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT false $$;
 ALTER TABLE contacts ALTER COLUMN id SET DEFAULT gen_random_uuid(); ALTER TABLE contacts ADD COLUMN first_name text; ALTER TABLE contacts ADD COLUMN last_name text; ALTER TABLE contacts ADD COLUMN company_name text;
 UPDATE contacts SET first_name='Test',last_name='Customer';
 ALTER TABLE contacts ADD COLUMN contact_name text; ALTER TABLE contacts ADD COLUMN username text; ALTER TABLE contacts ADD COLUMN office_id uuid REFERENCES company_offices(id); ALTER TABLE contacts ADD COLUMN created_by uuid;
 UPDATE contacts SET contact_name=full_name,username=id::text,office_id='${id(90)}';
 ALTER TABLE contacts ALTER COLUMN contact_name SET NOT NULL; ALTER TABLE contacts ALTER COLUMN username SET NOT NULL; ALTER TABLE contacts ADD UNIQUE(username); ALTER TABLE contacts ALTER COLUMN office_id SET NOT NULL;
 ALTER TABLE contacts DROP COLUMN full_name; ALTER TABLE contacts ADD COLUMN full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;
 ALTER TABLE monitoring_services ADD COLUMN organization_id uuid; ALTER TABLE monitoring_services ADD COLUMN is_active boolean DEFAULT true; ALTER TABLE monitoring_services ADD COLUMN monthly_price numeric DEFAULT 35;
 INSERT INTO monitoring_services(id,name,organization_id) VALUES('${id(70)}','Monitoring','${org}');
 ALTER TABLE security_contract_services ADD COLUMN organization_id uuid; ALTER TABLE security_contract_services ALTER COLUMN id SET DEFAULT gen_random_uuid();
 CREATE TABLE sales_orders(id uuid,organization_id uuid,contact_id uuid);
 ALTER TABLE security_contracts ALTER COLUMN id SET DEFAULT gen_random_uuid();
 ALTER TABLE security_contracts ADD COLUMN created_by_user_id uuid; ALTER TABLE security_contracts ADD COLUMN sales_order_id uuid; ALTER TABLE security_contracts ADD COLUMN price_override numeric;

 ALTER TABLE security_contracts ADD COLUMN completed_by_staff boolean; ALTER TABLE security_contracts ADD COLUMN account_type text; ALTER TABLE security_contracts ADD COLUMN account_services text[]; ALTER TABLE security_contracts ADD COLUMN is_monitoring boolean; ALTER TABLE security_contracts ADD COLUMN account_number text; ALTER TABLE security_contracts ADD COLUMN installation_date date; ALTER TABLE security_contracts ADD COLUMN service_account_numbers jsonb; ALTER TABLE security_contracts ADD COLUMN notes text; ALTER TABLE security_contracts ADD COLUMN email_override text; ALTER TABLE security_contracts ADD COLUMN approved_at timestamptz; ALTER TABLE security_contracts ADD COLUMN approved_by_user_id uuid; ALTER TABLE security_contracts ADD COLUMN rejection_reason text; ALTER TABLE security_contracts ADD COLUMN invitation_sent_at timestamptz; ALTER TABLE security_contracts ADD COLUMN invitation_sent_by_user_id uuid;
 `);
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002142729_security_onboarding_staff_workflows.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002170404_security_activation_billing_dates.sql',import.meta.url),'utf8'));
 await db.exec(`ALTER TABLE invoices ADD COLUMN created_by uuid; UPDATE invoices SET created_by='${id(11)}'; ALTER TABLE invoices ALTER COLUMN created_by SET NOT NULL;
 CREATE FUNCTION public.generate_invoice_number() RETURNS text LANGUAGE sql AS $$ SELECT 'INV-'||gen_random_uuid()::text $$;`);
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002171153_security_billing_invoice_schema.sql',import.meta.url),'utf8'));
 await db.exec('ALTER TABLE contacts DROP COLUMN tax_environment');
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002171432_security_billing_tax_environment.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002172438_security_billing_schedule_safeguards.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/20261002172637_security_shared_activation_mandate.sql',import.meta.url),'utf8'));
 const staff=async(action,cid=null,payload={})=>(await db.query('select public.staff_security_onboarding($1,$2,$3) result',[action,cid,JSON.stringify(payload)])).rows[0].result;
 const create={request_id:id(71),template_id:template,contact_id:contact,service_ids:[id(70)],term_months:12,account_type:'residential'};
 await role('authenticated',id(12));await assert.rejects(staff('create',null,create),'Organization membership does not grant onboarding access');
 await role('authenticated',id(1));await assert.rejects(staff('create',null,create),'Portal users cannot create staff agreements');
 assert.equal((await db.query('select count(*) from security_contracts')).rows[0].count,0,'Portal users cannot bypass RPC via staff table policies');
 await role('authenticated',id(11));
 await assert.rejects(staff('create',null,{...create,term_months:18}));
 await assert.rejects(staff('create',null,{...create,service_ids:[id(999)]}));
 let created=await staff('create',null,create);
 assert.equal((await staff('create',null,create)).id,created.id,'Creation retries return the same agreement');
 let view=await staff('get',created.id);assert.equal(view.document.term_months,12);
 await role('postgres');const printBefore=(await db.query('select (select count(*) from contacts) customers,(select count(*) from security_contracts) contracts')).rows[0];
 await role('authenticated',id(11));
 for (const term of [12,24,36,48,60]) { const blank=await staff('print_form',null,{template_id:template,service_ids:[id(70)],term_months:term});assert.equal(blank.term_months,term);assert.equal(blank.monthly_price,35);assert.ok(blank.autopay_authorization); }
 await assert.rejects(staff('print_form',null,{template_id:template,service_ids:[id(70)],term_months:18}));
 await assert.rejects(staff('print_form',null,{template_id:id(71),service_ids:[id(70)],term_months:36}));
 await role('authenticated',id(12));await assert.rejects(staff('print_form',null,{template_id:template,service_ids:[id(70)],term_months:36}));
 await role('postgres');assert.deepEqual((await db.query('select (select count(*) from contacts) customers,(select count(*) from security_contracts) contracts')).rows[0],printBefore,'Printing creates no customer or agreement');
 await role('authenticated',id(11));
 // A failed service insert must roll back the new customer and agreement.
 await role('postgres');await db.exec(`CREATE FUNCTION fail_staff_service() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF current_setting('test.fail_service',true)='true' THEN RAISE EXCEPTION 'Service unavailable'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_staff_service BEFORE INSERT ON security_contract_services FOR EACH ROW EXECUTE FUNCTION fail_staff_service(); SET test.fail_service='true';`);
 const before=(await db.query('select count(*) from contacts')).rows[0].count;
 await role('authenticated',id(11));await assert.rejects(staff('create',null,{...create,request_id:id(72),contact_id:null,new_contact:{first_name:'Rollback',last_name:'Customer',email:'rollback@example.com'}}));
 await role('postgres');assert.equal((await db.query('select count(*) from contacts')).rows[0].count,before,'Failed service save rolls back customer creation');await db.exec("SET test.fail_service='false'; update security_payment_methods set verified_at=now() where id='"+id(13)+"'");
 await role('authenticated',id(11));
 const newCustomer=await staff('create',null,{...create,request_id:id(91),contact_id:null,new_contact:{first_name:'New',last_name:'Customer',email:'new@example.com'}});
 await role('postgres');
 const addedContact=(await db.query('select ct.* from contacts ct join security_contracts c on c.contact_id=ct.id where c.id=$1',[newCustomer.id])).rows[0];
 assert.equal(addedContact.contact_name,'New Customer');assert.equal(addedContact.full_name,'New Customer');assert.equal(addedContact.office_id,id(90));assert.equal(addedContact.created_by,id(11));assert.ok(addedContact.username);
 await db.exec('update company_offices set is_active=false');
 await role('authenticated',id(11));
 await assert.rejects(staff('create',null,{...create,request_id:id(92),contact_id:null,new_contact:{first_name:'No',last_name:'Office',email:'no-office@example.com'}}),/active company office/);
 await role('postgres');await db.exec('update company_offices set is_active=true');
 await role('authenticated',id(11));
 await staff('edit',newCustomer.id,{...create,contact_id:addedContact.id,contact_edits:{first_name:'Corrected',last_name:'Customer',email:'new@example.com'}});
 await role('postgres');
 assert.equal((await db.query('select contact_name from contacts where id=$1',[addedContact.id])).rows[0].contact_name,'Corrected Customer');
 await db.query("update security_contracts set status='pending_customer' where id=$1",[created.id]);
 await role('authenticated',id(1));
 const originalMandate=(await rpc('get',id(5))).document.autopay_authorization;
 assert.ok(originalMandate.includes('Billing begins when monitoring is activated'),'Existing signed mandate stays intact');
 const portalMandate=(await rpc('get',created.id)).document.autopay_authorization;
 assert.ok(portalMandate.includes('Completing this form does not activate monitoring'),'New customer mandate explains staff scheduling');
 await role('authenticated',id(11));
 assert.equal(view.document.autopay_authorization,portalMandate,'Staff and customer entry retain the same recurring-payment mandate');
 const paper={paper_signed:true,autopay_accepted:true,document_version:view.document_version,account_type:'residential',form_data:form};
 await assert.rejects(staff('paper',created.id,{...paper,form_data:{...form,paymentMethodId:'manual_entry'}}),'Manual marker is never a payment credential');
 await assert.rejects(staff('paper',created.id,{...paper,autopay_accepted:false}));
 await assert.rejects(staff('paper',created.id,{...paper,form_data:{...form,propertyInfo:{...form.propertyInfo,zip_code:'bad'}}}));
 await staff('paper',created.id,paper);view=await staff('get',created.id);assert.equal(view.status,'pending_approval');
 assert.equal(view.document.propertyInfo.address_line1,form.propertyInfo.address_line1);
 await assert.rejects(staff('paper',created.id,paper),'Repeated entry cannot overwrite acceptance');
 await assert.rejects(staff('edit',created.id,create));
 await assert.rejects(db.query('update security_contracts set monthly_price=1 where id=$1',[created.id]));
 await assert.rejects(db.query("update security_contracts set status='active' where id=$1",[created.id]),'Activation requires approval');
 await db.query('select public.security_correct_onboarding($1,0,$2,$3)',[created.id,JSON.stringify({monitoring_tax_classification_id:id(20)}),'Tax classification']);
 await staff('approve',created.id,{revision:1});
 await assert.rejects(staff('activate',created.id,{revision:1}),/Set the monitoring start/);
 const activationDates=(await db.query("select ((now() at time zone 'America/Chicago')::date+5)::text start, ((now() at time zone 'America/Chicago')::date+15)::text first")).rows[0];
 await assert.rejects(staff('activate',created.id,{revision:1,monitoring_start_date:'2020-01-01',first_payment_date:activationDates.first}),/more than 31 days/);
 await assert.rejects(staff('activate',created.id,{revision:1,monitoring_start_date:activationDates.first,first_payment_date:activationDates.start}),/cannot precede/);
 await assert.rejects(staff('activate',created.id,{revision:1,monitoring_start_date:activationDates.start,first_payment_date:activationDates.start}),/at least 10 days/);
 await staff('activate',created.id,{revision:1,monitoring_start_date:activationDates.start,first_payment_date:activationDates.first});
 const scheduled=(await staff('get',created.id)).summary;
 assert.equal(scheduled.start_date,activationDates.start);assert.equal(scheduled.first_payment_date,activationDates.first);assert.equal(scheduled.first_payment_made_at,null);
 await assert.rejects(db.query("update security_contracts set first_payment_date=current_date where id=$1",[created.id]),/Activation dates/);
 await assert.rejects(db.query('select public.security_correct_onboarding($1,1,$2,$3)',[created.id,JSON.stringify({first_payment_date:activationDates.first}),'Customer requested date']));
 await role('service_role');
 const generate=async()=>(await db.query("select public.security_recurring_billing('generate',null,'{}') result")).rows[0].result;
 assert.equal((await generate()).generated,1,'Upcoming monitoring period is invoiced in time for advance notice');assert.equal((await generate()).generated,0);
 await role('postgres');
 const invoice=(await db.query('select i.due_date::text due, b.period_start::text start from invoices i join security_billing_cycles b on b.invoice_id=i.id where b.contract_id=$1',[created.id])).rows[0];
 assert.equal(invoice.due,activationDates.first);assert.equal(invoice.start,activationDates.start);
 assert.equal((await db.query('select private.security_contract_summary($1) summary',[created.id])).rows[0].summary.months_remaining,12,'Future start never displays more than the full initial term');
 await db.query("insert into payments(invoice_id,amount,payment_method) select invoice_id,1,'check' from security_billing_cycles where contract_id=$1",[created.id]);
 assert.ok((await db.query('select private.security_contract_summary($1) summary',[created.id])).rows[0].summary.first_payment_made_at,'Manual invoice receipts also supply first confirmed payment date');
 await role('authenticated',id(11));
 // Submitted fields are intentionally editable only through the audited workflow.
 const reviewContract=await staff('create',null,{...create,request_id:id(78)});
 const reviewDoc=await staff('get',reviewContract.id);
 await staff('paper',reviewContract.id,{...paper,document_version:reviewDoc.document_version});
 const correct=async(revision,patch,reason='Customer requested correction')=>(await db.query('select public.security_correct_onboarding($1,$2,$3,$4) result',[reviewContract.id,revision,JSON.stringify(patch),reason])).rows[0].result;
 await role('authenticated',id(12));await assert.rejects(correct(0,{notes:'No permission'}));
 await role('authenticated',id(11));
 await assert.rejects(correct(0,{status:'active'}),'Correction cannot bypass completion state');
 await assert.rejects(correct(0,{propertyInfo:{zip_code:'invalid'}}));
 await assert.rejects(correct(0,{notes:'No reason'},''));
 assert.equal((await correct(0,{service_account_numbers:{alarm_com:'123456',telguard:'TG-1'}})).revision,1);
 await assert.rejects(correct(0,{notes:'Stale tab'}),'Concurrent correction is rejected');
 await correct(1,{personalInfo:{phone:'5559998888'},propertyInfo:{address_line1:'2 Corrected Street'}});
 await correct(2,{monthly_price:45,term_months:24,contract_terms:'Corrected reviewed terms [term].'});
 await correct(3,{emergencyContacts:[{name:'Updated First',phone:'5551111111',password:'new-one',canAuthorize:true},{name:'Updated Second',phone:'5552222222',password:'new-two',canAuthorize:false}]});
 let corrected=(await db.query('select * from security_contracts where id=$1',[reviewContract.id])).rows[0];
 assert.equal(corrected.service_account_numbers.alarm_com,'123456');
 assert.equal(corrected.onboarding_agreement_snapshot.personalInfo.phone,'5559998888');
 assert.equal(corrected.onboarding_agreement_snapshot.propertyInfo.address_line1,'2 Corrected Street');
 assert.equal(corrected.onboarding_original_snapshot.document.monthly_price,35,'Original signed price is retained');
 assert.equal(corrected.onboarding_original_snapshot.document.term_months,12,'Original signed term is retained');
 assert.equal(corrected.onboarding_revision,4);assert.equal(corrected.status,'pending_approval');
 assert.equal((await db.query('select count(*) from security_onboarding_corrections where contract_id=$1',[reviewContract.id])).rows[0].count,4);
 await assert.rejects(db.query("update security_contracts set onboarding_original_snapshot='{}' where id=$1",[reviewContract.id]),'Original submission cannot be overwritten directly');
 await correct(4,{monitoring_tax_classification_id:id(20)});
 await assert.rejects(staff('approve',reviewContract.id,{revision:4}),'Approval cannot act on a stale reviewed revision');
 await staff('approve',reviewContract.id,{revision:5});
 await correct(5,{notes:'Final account setup'});
 assert.equal((await staff('get',reviewContract.id)).status,'pending_approval','Approved corrections return for review');
 // Even a manager must have the existing Contract Management capability.
 await role('postgres');await db.exec(`CREATE OR REPLACE FUNCTION public.get_user_module_access(p_user uuid,p_module uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT p_user='${id(12)}'::uuid $$;`);
 await role('authenticated',id(12));await correct(6,{account_number:'Manager entered'});
 await role('postgres');await db.exec('CREATE OR REPLACE FUNCTION public.get_user_module_access(p_user uuid,p_module uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT false $$;');
 await role('authenticated',id(11));
 await correct(7,{security_billing_mode:'mail'});
 corrected=(await db.query('select * from security_contracts where id=$1',[reviewContract.id])).rows[0];
 assert.equal(Number(corrected.monthly_price),52);assert.equal(Number(corrected.mail_invoice_fee),7);
 assert.equal(corrected.onboarding_agreement_snapshot.autopay_authorization,null);
 assert.equal(Number(corrected.onboarding_agreement_snapshot.monthly_price),52,'Corrected snapshot includes the mailing fee once');
 await assert.rejects(correct(8,{security_billing_mode:'autopay'}),'Removing mail exception requires verified AutoPay');
 await correct(8,{security_billing_mode:'autopay',paymentMethodId:id(13),autopay_accepted:true});
 corrected=(await db.query('select * from security_contracts where id=$1',[reviewContract.id])).rows[0];
 assert.equal(Number(corrected.monthly_price),45);assert.equal(Number(corrected.onboarding_agreement_snapshot.mail_invoice_fee),0);assert.equal(corrected.onboarding_agreement_snapshot.autopay_authorization,portalMandate);
 assert.equal(corrected.onboarding_original_snapshot.document.monthly_price,35);
 // The decorated portal submit still mirrors the accepted property atomically.
 const portalContract=await staff('create',null,{...create,request_id:id(88)});
 await db.query("update security_contracts set status='pending_customer',magic_link_token=$1,magic_link_expires_at=now()+interval '1 day' where id=$2",[id(89),portalContract.id]);
 await role('anon');const portalReview=await rpc('get',portalContract.id,id(89));
 await rpc('submit',portalContract.id,id(89),{revision:0,form_data:form,signature:'data:image/png;base64,aGVsbG8=',accepted:true,autopay_accepted:true,document_version:portalReview.document_version});
 await role('authenticated',id(11));
 assert.equal((await db.query('select property_address from security_contracts where id=$1',[portalContract.id])).rows[0].property_address,form.propertyInfo.address_line1);
 // Invitation preparation does not invalidate the delivered link on provider failure.
 const unsigned=await staff('create',null,{...create,request_id:id(73),contact_id:otherContact});
 await db.query('update security_contracts set magic_link_token=$1 where id=$2',[id(74),unsigned.id]);
 const prepare=async req=>(await db.query('select public.security_prepare_invitation($1,$2) result',[unsigned.id,req])).rows[0].result;
 const attempt=await prepare(id(75));assert.equal((await prepare(id(76))).id,attempt.id,'Uncertain retries reuse the provider idempotency key');
 assert.equal((await db.query('select magic_link_token from security_contracts where id=$1',[unsigned.id])).rows[0].magic_link_token,id(74));
 await assert.rejects(db.query('select public.security_finish_invitation($1,$2)',[attempt.id,'mail-id']),'Staff cannot forge provider acceptance');
 await role('service_role');
 const msg={to:[attempt.recipient],subject:'Original',text:'Original'};
 const frozen=(await db.query('select public.security_invitation_message($1,$2) result',[attempt.id,JSON.stringify(msg)])).rows[0].result;
 const retry=(await db.query('select public.security_invitation_message($1,$2) result',[attempt.id,JSON.stringify({...msg,subject:'Changed'})])).rows[0].result;
 assert.deepEqual(retry,frozen,'Provider payload remains identical after template changes');
 await db.query('select public.security_finish_invitation($1,$2)',[attempt.id,'mail-id']);await db.query('select public.security_finish_invitation($1,$2)',[attempt.id,'mail-id']);
 await role('postgres');assert.equal((await db.query('select magic_link_token from security_contracts where id=$1',[unsigned.id])).rows[0].magic_link_token,attempt.token);
 console.log('Staff onboarding tests passed: module access, atomic creation/rollback/retries, shared form validation, real verified payment, signed entry, immutable terms, approval before activation, audited field corrections, preserved original submission, concurrent edits, manager permissions, and invitation delivery reconciliation.');
}
