import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
let queue=[],calls=[],sessionUser='tech',online=true;
let mode='success';let savedRecord;
const storage={getSyncQueue:async()=>queue.map(a=>({...a})),removeFromSyncQueue:async id=>{queue=queue.filter(a=>a.id!==id);}};
const supabase={auth:{getSession:async()=>({data:{session:{user:{id:sessionUser}}},error:null})},from(table){let op,data;
 const q=new Proxy({}, {get(_,key){if(key==='then')return resolve=>{calls.push({table,op,data});if(mode==='duplicate'){resolve(op==='insert'?{error:{code:'23505'},data:null}:{error:null,data:savedRecord});return;}resolve(mode==='denied'?{error:{message:'Manager approval required'},data:null}:mode==='invisible'?{error:null,data:[]}:{error:null,data:op==='insert'?null:[{id:data?.id}]});};return(...args)=>{if(['insert','update','delete'].includes(key)){op=key;data=args[0];}return q;};}});return q;}};
const module={exports:{}};
vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/syncManager.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports,console:{error(){}},navigator:{get onLine(){return online;}},require(name){if(name==='./supabase')return {supabase};if(name==='./offlineStorage')return {offlineStorage:storage};throw Error(name);}});
const sync=module.exports.syncManager;
const action=(id,type,timestamp,ownerId='tech')=>({id,type,timestamp,ownerId,table:'time_entries',data:{id:'entry',clock_out:type==='update'?'2026-10-02T12:00Z':undefined,synced:false}});
queue=[action('stop','update',2),action('start','create',1)];await sync.syncQueuedActions();
assert.deepEqual(calls.map(c=>c.op),['insert','update'],'Queued creation precedes its update');
assert.equal(calls[0].data.id,'entry','Client ID is preserved');assert.equal('synced' in calls[0].data,false);assert.equal(queue.length,0);
mode='denied';calls=[];queue=[action('stop','update',2),action('start','create',1)];await sync.syncQueuedActions();
assert.equal(queue.length,2,'Rejected saves are retained');assert.deepEqual(calls.map(c=>c.op),['insert'],'Dependent same-row update is held');assert.equal(await sync.getQueueLength(),2);
mode='invisible';calls=[];queue=[action('stop','update',1)];await sync.syncQueuedActions();assert.equal(queue.length,1,'A zero-row RLS update remains pending');
mode='success';sessionUser='other';calls=[];await sync.syncQueuedActions();assert.equal(calls.length,0,'A different signed-in account cannot sync another employee queue');assert.equal(queue.length,1);
sessionUser='tech';queue=[action('legacy','update',1,undefined)];delete queue[0].ownerId;await sync.syncQueuedActions();assert.equal(queue.length,1,'Unowned legacy actions await review rather than being attributed to the current account');
queue=[action('stop','update',1)];online=false;calls=[];await sync.syncQueuedActions();assert.equal(calls.length,0);assert.equal(queue.length,1);
online=true;await sync.syncQueuedActions();assert.equal(queue.length,0,'A later authorized retry succeeds');
console.log('Offline sync preserves IDs, orders writes, retains rejected/zero-row saves, and isolates account-owned queues.');
// Lost acknowledgement of a successful creation is safe to retry only when the visible record matches.
mode='duplicate';queue=[action('start','create',1)];calls=[];savedRecord={id:'entry',clock_out:null,created_at:'2026-10-02T12:00:00+00:00'};
queue[0].data.created_at='2026-10-02T12:00:00.000Z';await sync.syncQueuedActions();assert.equal(queue.length,0);
queue=[action('start','create',1)];queue[0].data.clock_out=null;savedRecord={id:'entry',clock_out:'2026-10-02T14:00Z'};await sync.syncQueuedActions();assert.equal(queue.length,1,'A different already-existing record must remain a conflict');
mode='success';
const storageModule={exports:{}};let savedAction,abortWrite=false;
vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/offlineStorage.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module:storageModule,exports:storageModule.exports,Date,crypto:{randomUUID:()=> 'queued-id'},require:()=>({supabase}),queueMicrotask});
const durableStorage=storageModule.exports.offlineStorage;
durableStorage.db={transaction(){const txn={error:new Error('Storage transaction aborted'),objectStore(){return {add(action){savedAction=action;queueMicrotask(()=>abortWrite?txn.onabort():txn.oncomplete());},delete(){queueMicrotask(()=>abortWrite?txn.onabort():txn.oncomplete());}};}};return txn;}};
await durableStorage.addToSyncQueue({type:'update',table:'time_entries',data:{id:'entry',clock_out:'2026-10-02T12:00Z'}});
assert.equal(savedAction.ownerId,'tech');assert.equal(savedAction.id,'queued-id');
abortWrite=true;await assert.rejects(()=>durableStorage.addToSyncQueue({type:'update',table:'time_entries',data:{id:'entry'}}),/transaction aborted/);
await assert.rejects(()=>durableStorage.removeFromSyncQueue('queued-id'),/transaction aborted/);
console.log('Offline queue saves/removals wait for durable transaction completion and reject aborted writes.');
