import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { AlertTriangle, CheckCircle2, Clock3, ListTodo, Users, Wifi, WifiOff, Wrench } from 'lucide-react';

type TechStatus = 'available' | 'on_job' | 'traveling';
interface Tech { id:string; name:string; clockInTime:string; status:TechStatus; currentJob:string|null; jobTitle:string|null }
interface WorkOrder { id:string; work_order_number:string; title:string; status:string; assigned_to_name:string|null; start_date:string; needs_info:boolean; blocked_reason:string|null }
interface ServiceRequest { id:string; service_request_number:string; description:string; status:string; created_at:string; contact_name:string|null }
interface PunchItem { id:string; description:string; status:string; created_at:string; project_name:string|null }
interface Project { id:string; name:string; status:string; created_at:string; target_completion_date:string|null; contact_name:string|null }

const SERVICE_STATUSES=['pending','in_progress','dispatched'];
const PUNCH_STATUSES=['pending','submitted','in_progress'];
const CLOSED_WO='("cancelled","archived")';
const CLOSED_PROJECT='("completed","cancelled")';
const norm=(s?:string|null)=>(s||'').toLowerCase().replace(/\s+/g,'_');
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const yesterdayKey=()=>{const d=new Date();d.setDate(d.getDate()-1);return dateKey(d)};
const age=(s:string)=>{const m=Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/60000));return m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`};
const clock=(s:string)=>new Date(s).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});

export default function TVDashboard(){
 const [techs,setTechs]=useState<Tech[]>([]); const [today,setToday]=useState<WorkOrder[]>([]); const [yesterday,setYesterday]=useState<WorkOrder[]>([]);
 const [service,setService]=useState<ServiceRequest[]>([]); const [punch,setPunch]=useState<PunchItem[]>([]); const [projects,setProjects]=useState<Project[]>([]);
 const [orgName,setOrgName]=useState(''); const [orgLogo,setOrgLogo]=useState(''); const [connected,setConnected]=useState(true); const [lastUpdate,setLastUpdate]=useState(new Date()); const [now,setNow]=useState(new Date());
 useEffect(()=>{const t=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(t)},[]);
 const loadOrg=useCallback(async()=>{const {data,error}=await supabase.from('organizations').select('name,logo_url').limit(1).maybeSingle();if(error)throw error;if(data){setOrgName(data.name||'');setOrgLogo(data.logo_url||'')}},[]);
 const loadTechs=useCallback(async()=>{const [{data:clocks,error:ce},{data:wos,error:we}]=await Promise.all([supabase.from('daily_clock_entries').select('technician_id,clock_in,profiles:technician_id(id,first_name,last_name)').is('clock_out',null).order('clock_in',{ascending:true}),supabase.from('work_orders').select('work_order_number,title,assigned_to,status').in('status',['in_progress','traveling','on_site'])]);if(ce)throw ce;if(we)throw we;const map=new Map<string,Tech>();(clocks||[]).forEach((e:any)=>{if(!e.profiles||map.has(e.technician_id))return;const wo=wos?.find((w:any)=>w.assigned_to===e.technician_id);map.set(e.technician_id,{id:e.technician_id,name:`${e.profiles.first_name||''} ${e.profiles.last_name||''}`.trim(),clockInTime:e.clock_in,status:!wo?'available':norm(wo.status)==='traveling'?'traveling':'on_job',currentJob:wo?.work_order_number||null,jobTitle:wo?.title||null})});setTechs([...map.values()])},[]);
 const loadWorkOrders=useCallback(async()=>{const [t,y]=await Promise.all([supabase.from('work_orders').select('id,work_order_number,title,status,assigned_to_name,start_date,needs_info,blocked_reason').eq('start_date',dateKey()).not('status','in',CLOSED_WO).order('work_order_number'),supabase.from('work_orders').select('id,work_order_number,title,status,assigned_to_name,start_date,needs_info,blocked_reason').eq('start_date',yesterdayKey()).not('status','in',CLOSED_WO).order('work_order_number')]);if(t.error)throw t.error;if(y.error)throw y.error;setToday((t.data||[]) as WorkOrder[]);setYesterday((y.data||[]) as WorkOrder[])},[]);
 const loadService=useCallback(async()=>{const {data,error}=await supabase.from('service_requests').select('id,service_request_number,description,status,created_at,contacts(full_name)').in('status',SERVICE_STATUSES).order('created_at',{ascending:true}).limit(40);if(error)throw error;setService((data||[]).map((x:any)=>({...x,contact_name:x.contacts?.full_name||null})))},[]);
 const loadPunch=useCallback(async()=>{const {data,error}=await supabase.from('punchlist_tasks').select('id,description,status,created_at,projects(name)').in('status',PUNCH_STATUSES).order('created_at',{ascending:true}).limit(40);if(error)throw error;setPunch((data||[]).map((x:any)=>({...x,project_name:x.projects?.name||null})))},[]);
 const loadProjects=useCallback(async()=>{const {data,error}=await supabase.from('projects').select('id,name,status,created_at,target_completion_date,contacts(full_name)').not('status','in',CLOSED_PROJECT).order('created_at',{ascending:false}).limit(40);if(error)throw error;setProjects((data||[]).map((x:any)=>({...x,contact_name:x.contacts?.full_name||null})))},[]);
 const refresh=useCallback(async()=>{try{await Promise.all([loadOrg(),loadTechs(),loadWorkOrders(),loadService(),loadPunch(),loadProjects()]);setConnected(true);setLastUpdate(new Date())}catch(e){console.error('Production TV refresh failed',e);setConnected(false)}},[loadOrg,loadTechs,loadWorkOrders,loadService,loadPunch,loadProjects]);
 useEffect(()=>{refresh();const fallback=window.setInterval(refresh,30000);const ch=[['daily_clock_entries','clock'],['work_orders','wo'],['service_requests','service'],['punchlist_tasks','punch'],['projects','projects']].map(([table,key])=>supabase.channel(`production-tv-${key}`).on('postgres_changes',{event:'*',schema:'public',table},refresh).subscribe());return()=>{window.clearInterval(fallback);ch.forEach(c=>supabase.removeChannel(c))}},[refresh]);
 const incompleteYesterday=yesterday.filter(w=>!['completed','complete','closed'].includes(norm(w.status))).length;
 return <div className="fixed inset-0 overflow-hidden bg-slate-950 text-white"><div className="mx-auto flex h-full w-full max-w-[3840px] flex-col">
  <header className="flex h-[8.5vh] min-h-[86px] shrink-0 items-center justify-between border-b border-slate-800 px-[1.4vw]">
   <div className="flex items-center gap-[1vw]">{orgLogo&&<img src={orgLogo} alt="" className="h-[5vh] max-h-16 max-w-[12vw] object-contain"/>}<div><div className="text-[clamp(12px,.75vw,28px)] font-bold uppercase tracking-[.2em] text-slate-500">{orgName||'MyJobView'}</div><h1 className="text-[clamp(26px,1.75vw,64px)] font-black leading-none">Production</h1></div></div>
   <div className="flex items-center gap-[2vw]"><div className={`flex items-center gap-2 rounded-full border px-[.7vw] py-[.35vw] text-[clamp(12px,.65vw,24px)] font-bold ${connected?'border-emerald-500/30 text-emerald-300':'border-red-500/30 text-red-300'}`}>{connected?<Wifi/>:<WifiOff/>}{connected?'LIVE':'OFFLINE'} · {age(lastUpdate.toISOString())}</div><div className="text-right"><div className="font-mono text-[clamp(28px,1.8vw,68px)] font-black leading-none">{now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</div><div className="text-[clamp(12px,.7vw,26px)] font-semibold uppercase text-slate-400">{now.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</div></div></div>
  </header>
  <div className="flex h-[4.8vh] min-h-[48px] shrink-0 items-center gap-[2vw] border-b border-slate-800 bg-slate-900/70 px-[1.4vw] text-[clamp(13px,.78vw,30px)] font-bold"><Stat n={techs.length} label="TECHS CLOCKED IN"/><Stat n={today.length} label="TODAY"/><Stat n={service.length} label="OPEN SERVICE" warn={service.some(s=>Date.now()-new Date(s.created_at).getTime()>86400000)}/><Stat n={punch.length} label="PUNCHLIST" warn={punch.some(p=>Date.now()-new Date(p.created_at).getTime()>604800000)}/><Stat n={projects.length} label="ACTIVE PROJECTS"/><span className="ml-auto text-slate-500">AUTO-REFRESH 30 SEC</span></div>
  <main className="grid min-h-0 flex-1 grid-cols-2 grid-rows-3 gap-[.7vw] p-[.7vw]">
   <Panel title="Today's Work Orders" count={today.length} icon={<ListTodo/>}><WOList items={today} empty="No work orders scheduled today"/></Panel>
   <Panel title="Techs Clocked In" count={techs.length} icon={<Users/>}><TechList items={techs}/></Panel>
   <Panel title="Yesterday's Work Orders" count={yesterday.length} badge={incompleteYesterday?`${incompleteYesterday} UNFINISHED`:undefined} icon={<CheckCircle2/>}><WOList items={yesterday} yesterday empty="No work orders yesterday"/></Panel>
   <Panel title="Open Service Requests" count={service.length} subtitle="NEED TO BE SCHEDULED" icon={<Clock3/>}><ServiceList items={service}/></Panel>
   <Panel title="Open Punchlist Items" count={punch.length} subtitle="NEED TO BE SCHEDULED" icon={<Wrench/>}><PunchList items={punch}/></Panel>
   <Panel title="Newest Projects" count={projects.length} subtitle="MOST RECENT FIRST" icon={<AlertTriangle/>}><ProjectList items={projects}/></Panel>
  </main>
 </div></div>
}
function Stat({n,label,warn=false}:{n:number;label:string;warn?:boolean}){return <div className="flex items-baseline gap-2"><b className={warn?'text-amber-400':'text-sky-400'}>{n}</b><span className="text-slate-300">{label}</span></div>}
function Panel({title,count,subtitle,badge,icon,children}:{title:string;count:number;subtitle?:string;badge?:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-slate-800 bg-slate-900/45"><div className="flex h-[4.8vh] min-h-[48px] shrink-0 items-center gap-[.55vw] border-b border-slate-800 px-[.8vw]"><span className="text-sky-400 [&>svg]:h-[1.15vw] [&>svg]:w-[1.15vw]">{icon}</span><h2 className="text-[clamp(15px,.92vw,34px)] font-black uppercase tracking-wide">{title}</h2><span className="rounded bg-slate-800 px-2 py-1 text-[clamp(12px,.65vw,24px)] font-black text-slate-300">{count}</span>{subtitle&&<span className="text-[clamp(10px,.55vw,20px)] font-bold tracking-wider text-slate-500">{subtitle}</span>}{badge&&<span className="ml-auto rounded bg-red-500/15 px-2 py-1 text-[clamp(10px,.6vw,22px)] font-black text-red-400">{badge}</span>}</div><div className="min-h-0 flex-1 overflow-hidden">{children}</div></section>}
const row='grid min-h-[34px] items-center border-b border-slate-800/70 px-[.8vw] text-[clamp(12px,.72vw,27px)] leading-tight';
function WOList({items,yesterday=false,empty}:{items:WorkOrder[];yesterday?:boolean;empty:string}){if(!items.length)return <Empty text={empty}/>;return <div>{items.slice(0,7).map(w=>{const done=['completed','complete','closed'].includes(norm(w.status));const problem=w.needs_info||norm(w.status)==='blocked'||(yesterday&&!done);return <div key={w.id} className={`${row} grid-cols-[.7fr_2.1fr_1.2fr_1fr] ${problem?'bg-red-500/5':''}`}><b className="font-mono text-sky-300">{w.work_order_number}</b><span className="truncate font-semibold">{w.title}</span><span className="truncate text-slate-400">{w.assigned_to_name||'UNASSIGNED'}</span><Status status={done?'complete':w.status} problem={problem}/></div>})}{items.length>7&&<More n={items.length-7}/>}</div>}
function TechList({items}:{items:Tech[]}){if(!items.length)return <Empty text="No technicians currently clocked in"/>;return <div>{items.slice(0,7).map(t=><div key={t.id} className={`${row} grid-cols-[1.5fr_.7fr_1fr_1.6fr]`}><b>{t.name}</b><span className="font-mono text-slate-400">{clock(t.clockInTime)}</span><Status status={t.status}/><span className="truncate text-slate-400">{t.currentJob?`${t.currentJob} · ${t.jobTitle||''}`:'No active work order'}</span></div>)}{items.length>7&&<More n={items.length-7}/>}</div>}
function ServiceList({items}:{items:ServiceRequest[]}){if(!items.length)return <Empty text="No open service requests waiting to be scheduled"/>;return <div>{items.slice(0,7).map(s=>{const old=Date.now()-new Date(s.created_at).getTime()>86400000;return <div key={s.id} className={`${row} grid-cols-[.8fr_1.3fr_2.2fr_.55fr] ${old?'bg-amber-500/5':''}`}><b className="font-mono text-sky-300">{s.service_request_number}</b><span className="truncate font-semibold">{s.contact_name||'No customer'}</span><span className="truncate text-slate-400">{s.description}</span><b className={old?'text-amber-400':'text-slate-400'}>{age(s.created_at)}</b></div>})}{items.length>7&&<More n={items.length-7}/>}</div>}
function PunchList({items}:{items:PunchItem[]}){if(!items.length)return <Empty text="No open punchlist items waiting to be scheduled"/>;return <div>{items.slice(0,7).map(p=>{const old=Date.now()-new Date(p.created_at).getTime()>604800000;return <div key={p.id} className={`${row} grid-cols-[1.4fr_2.8fr_.55fr] ${old?'bg-amber-500/5':''}`}><b className="truncate">{p.project_name||'Project'}</b><span className="truncate text-slate-400">{p.description}</span><b className={old?'text-amber-400':'text-slate-400'}>{age(p.created_at)}</b></div>})}{items.length>7&&<More n={items.length-7}/>}</div>}
function ProjectList({items}:{items:Project[]}){if(!items.length)return <Empty text="No active projects"/>;return <div>{items.slice(0,7).map(p=><div key={p.id} className={`${row} grid-cols-[2fr_1.2fr_.7fr_1fr]`}><b className="truncate">{p.name}</b><span className="truncate text-slate-400">{p.contact_name||'—'}</span><span className="font-bold text-sky-300">{age(p.created_at)}</span><Status status={p.status}/></div>)}{items.length>7&&<More n={items.length-7}/>}</div>}
function Status({status,problem=false}:{status:string;problem?:boolean}){const s=norm(status);const cls=problem?'text-red-400':s==='complete'||s==='completed'?'text-emerald-400':s==='traveling'?'text-sky-400':s==='on_job'||s==='on_site'||s==='in_progress'?'text-emerald-400':s==='available'?'text-amber-300':'text-slate-300';return <span className={`truncate font-black uppercase ${cls}`}>{problem?'⚠ ':''}{s.replace(/_/g,' ')}</span>}
function More({n}:{n:number}){return <div className="px-[.8vw] py-1 text-right text-[clamp(10px,.55vw,20px)] font-bold text-slate-500">+ {n} MORE</div>}
function Empty({text}:{text:string}){return <div className="flex h-full items-center justify-center text-[clamp(13px,.75vw,28px)] font-semibold text-slate-600">{text}</div>}
