import { useEffect, useMemo, useState } from 'react';
import { CheckCircle, Circle, Plus, Trash2, AlertCircle, Sparkles, Loader, Lock } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';

const sections = [
  ['customer_check_in','Customer Check-In',['Current problems/issues reviewed','Specific items customer wants checked','Customer/system information confirmed']],
  ['network_internet','Network & Internet',['Internet connection tested','Speed test recorded/reviewed','Router/gateway operating normally','Access points online','Wi-Fi coverage/issues reviewed','Firmware/software reviewed where appropriate']],
  ['av_automation','A/V & Automation',['Displays/TVs checked','Audio zones checked','Sources/streaming checked','Remotes/control interfaces checked','Automation checked','Lighting/shades checked if applicable']],
  ['security_surveillance','Security & Surveillance',['Security panel/system checked','Sensors/devices checked as appropriate','Cameras checked','Recording/playback checked','Doorbells/locks/access checked if applicable','Notifications and customer app reviewed']],
  ['room_by_room','Room / System Walk-Through',['Check all rooms with systems that are relevant to this VIP visit','Verify applicable installed systems are operating normally','Document any issue found or anything unable to be tested','Capture relevant notes/photos when helpful']],
  ['preventive_maintenance','Preventive Maintenance',['Equipment/rack visually inspected','Ventilation/cleanliness checked','Connections/cabling visually checked','Obvious UPS/battery backup alerts checked','Batteries/consumables replaced as needed','Firmware/software updated where appropriate']],
] as const;

const dispositions = [
  ['resolved_today','Resolved Today'],['punchlist','Add to Punchlist'],
  ['service_follow_up','Service Follow-Up'],['no_action','No Action']
] as const;

type Finding={id?:string;room:string;description:string;notes:string;dispositions:string[];punchlist_task_id?:string|null;service_request_id?:string|null;routed_at?:string|null};
type SalesLeadDraft={notes:string};

export default function VipMaintenanceChecklist({workOrderId,onChange,onAddPart}:{workOrderId:string;onChange?:()=>void;onAddPart?:()=>void}) {
 const {profile}=useAuth(); const [visit,setVisit]=useState<any>(null); const [findings,setFindings]=useState<Finding[]>([]); const [saving,setSaving]=useState(false);
 const [cleaningLead,setCleaningLead]=useState(false);
 const [leadDraft,setLeadDraft]=useState('');
 const [leadDraftDirty,setLeadDraftDirty]=useState(false);
 const readOnly=!!visit?.completed_at;
 useEffect(()=>{load();},[workOrderId]);
 async function load(){
  let {data:v}=await supabase.from('vip_maintenance_visits').select('*').eq('work_order_id',workOrderId).maybeSingle();
  if(!v&&profile?.organization_id){const r=await supabase.from('vip_maintenance_visits').insert({work_order_id:workOrderId,organization_id:profile.organization_id,created_by:profile.id}).select().single();v=r.data;}
  setVisit(v); if(v){setLeadDraft(v.responses?.sales_lead?.notes||'');setLeadDraftDirty(false);const {data}=await supabase.from('vip_maintenance_findings').select('*').eq('visit_id',v.id).order('created_at');setFindings(data||[]);}
 }
 const missing=useMemo(()=>{if(!visit)return ['VIP Maintenance']; const m:string[]=[];
  sections.forEach(([k,l])=>{const x=visit.responses?.[k];if(!x?.complete&&!(k!=='customer_check_in'&&x?.na))m.push(l);});
  if(!visit.responses?.customer_training?.complete&&!visit.training_not_needed&&!visit.customer_not_present)m.push('Customer Training');
  if(!visit.no_issues_found&&!findings.length)m.push('Findings / Issues');
  if(findings.some(f=>!f.dispositions?.length))m.push('Finding Dispositions');
  if(findings.some(f=>(f.dispositions||[]).includes('no_action')&&!f.notes?.trim()))m.push('No Action Reason');
  if(findings.some(f=>(f.dispositions||[]).some(d=>(d==='punchlist'&&!f.punchlist_task_id)||(d==='service_follow_up'&&!f.service_request_id))))m.push('Unrouted Findings');
  const lead=visit.responses?.sales_lead; if(!visit.no_opportunities_identified&&!lead?.notes?.trim())m.push('Sales Lead / No Sales Lead Identified');
  if(!visit.customer_not_present&&!visit.customer_acknowledged_at)m.push('Customer Acknowledgment'); return m;
 },[visit,findings]);
 async function patch(p:any){if(!visit||readOnly)return;setSaving(true);const next={...visit,...p,updated_at:new Date().toISOString()};setVisit(next);await supabase.from('vip_maintenance_visits').update(p).eq('id',visit.id);setSaving(false);onChange?.();}
 async function setSection(k:string,p:any){if(readOnly)return;await patch({responses:{...(visit.responses||{}),[k]:{...(visit.responses?.[k]||{}),...p}}});}
 async function addFinding(){if(!visit||!profile||readOnly)return;if(visit.no_issues_found)await patch({no_issues_found:false});const {data}=await supabase.from('vip_maintenance_findings').insert({visit_id:visit.id,organization_id:profile.organization_id,created_by:profile.id,description:'New finding'}).select().single();if(data)setFindings([...findings,data]);}
 async function updateFinding(f:Finding,p:any){if(readOnly)return;const next={...f,...p};setFindings(findings.map(x=>x.id===f.id?next:x));if(f.id)await supabase.from('vip_maintenance_findings').update(p).eq('id',f.id);}
 async function removeFinding(f:Finding){if(readOnly)return;if(f.id)await supabase.from('vip_maintenance_findings').delete().eq('id',f.id);setFindings(findings.filter(x=>x.id!==f.id));}
 async function routeFinding(f:Finding){if(!f.id||readOnly)return;setSaving(true);const {data,error}=await supabase.rpc('route_vip_maintenance_finding',{p_finding_id:f.id});setSaving(false);if(error){alert(error.message);return;}setFindings(findings.map(x=>x.id===f.id?data:x));onChange?.();}
 async function saveSalesLead(notes=leadDraft){if(readOnly||!visit)return;await patch({no_opportunities_identified:false,responses:{...(visit.responses||{}),sales_lead:{notes}}});setLeadDraftDirty(false);}
 useEffect(()=>{if(!leadDraftDirty||readOnly)return;const timer=setTimeout(()=>{void saveSalesLead(leadDraft);},700);return()=>clearTimeout(timer);},[leadDraft,leadDraftDirty,readOnly]);
 async function cleanSalesLead(){if(readOnly)return;const notes=leadDraft.trim();if(!notes||cleaningLead)return;setCleaningLead(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Please sign in again.');const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ai-assistant`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({mode:'cleanup_sales_lead',text:notes})});const data=await res.json();if(!res.ok||!data.cleaned)throw new Error(data.error||'Could not clean up notes');setLeadDraft(data.cleaned);setLeadDraftDirty(false);await saveSalesLead(data.cleaned);}catch(e){alert(e instanceof Error?e.message:'Could not clean up notes');}finally{setCleaningLead(false);}}
 if(!visit)return <div className="p-6 text-sm text-gray-500">Preparing VIP Maintenance checklist…</div>;
 return <div className="space-y-4 sm:space-y-5">
  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-lg font-bold text-gray-900">VIP Maintenance Visit</h3>{readOnly&&<span className="inline-flex items-center gap-1 rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600"><Lock className="w-3 h-3"/>Completed</span>}</div><p className="text-sm text-gray-600">{readOnly?'Completed VIP visit record. This checklist is read-only.':'Complete each applicable section. Any equipment, parts, batteries or other items added during the visit are selected from the product catalog and added to the Work Order Parts tab for invoicing.'}</p>{!readOnly&&onAddPart&&<button type="button" onClick={onAddPart} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-blue-600"><Plus className="w-3.5 h-3.5"/>Item (select from catalog)</button>}</div><span className={`text-xs px-2.5 py-1 rounded-full font-semibold ${readOnly?'bg-gray-100 text-gray-600':missing.length?'bg-amber-100 text-amber-700':'bg-green-100 text-green-700'}`}>{readOnly?'Completed':missing.length?missing.length+' incomplete':'Ready to complete'}</span></div>
  {sections.map(([k,label,checks])=>{const x=visit.responses?.[k]||{};return <fieldset key={k} disabled={readOnly} className={`rounded-xl border p-3.5 sm:p-4 ${x.na?'bg-gray-50 opacity-70':'bg-white'}`}><div className="flex items-start justify-between gap-3"><button onClick={()=>setSection(k,{complete:!x.complete,na:false})} className="flex min-h-11 items-center gap-2 text-left font-semibold text-gray-900 touch-manipulation">{x.complete?<CheckCircle className="w-5 h-5 text-green-600"/>:<Circle className="w-5 h-5 text-gray-400"/>}{label}</button>{k!=='customer_check_in'&&<label className="flex items-center gap-1.5 text-xs text-gray-500"><input type="checkbox" checked={!!x.na} onChange={e=>setSection(k,{na:e.target.checked,complete:false})}/>N/A</label>}</div>{!x.na&&<><div className="mt-3 grid gap-1.5">{checks.map(check=><div key={check} className="text-xs text-gray-600 flex items-start gap-2"><CheckCircle className="w-3.5 h-3.5 mt-0.5 text-gray-400 shrink-0"/>{check}</div>)}</div><textarea value={x.notes||''} onChange={e=>setSection(k,{notes:e.target.value})} rows={2} placeholder="Notes (optional)" className="mt-3 w-full border border-gray-200 rounded-lg p-3 text-base sm:text-sm"/></>}</fieldset>})}
  <fieldset disabled={readOnly} className="rounded-xl border p-4"><div className="flex items-center justify-between"><button onClick={()=>setSection('customer_training',{complete:!visit.responses?.customer_training?.complete})} className="flex items-center gap-2 font-semibold">{visit.responses?.customer_training?.complete?<CheckCircle className="w-5 h-5 text-green-600"/>:<Circle className="w-5 h-5 text-gray-400"/>}Customer Training</button><label className="text-xs text-gray-600 flex gap-1.5"><input type="checkbox" checked={visit.training_not_needed} onChange={e=>patch({training_not_needed:e.target.checked})}/>No customer present / training not needed</label></div></fieldset>
  <fieldset disabled={readOnly} className="rounded-xl border p-4 space-y-3"><div className="flex justify-between"><h4 className="font-semibold">Findings / Issues</h4><label className="text-xs flex gap-1.5"><input type="checkbox" checked={visit.no_issues_found} onChange={e=>{if(e.target.checked&&findings.length){alert('Remove the documented findings before selecting No Issues Found.');return;}patch({no_issues_found:e.target.checked});}}/>No Issues Found</label></div>
   {findings.map(f=><div key={f.id} className="border rounded-lg p-3 space-y-2"><div className="flex gap-2"><input value={f.room||''} onChange={e=>updateFinding(f,{room:e.target.value})} placeholder="Room" className="w-32 border rounded p-2 text-sm"/><input value={f.description} onChange={e=>updateFinding(f,{description:e.target.value})} className="flex-1 border rounded p-2 text-sm"/><button onClick={()=>removeFinding(f)}><Trash2 className="w-4 h-4 text-gray-400"/></button></div><textarea value={f.notes||''} onChange={e=>updateFinding(f,{notes:e.target.value})} placeholder={(f.dispositions||[]).includes('no_action')?'Reason required for No Action':'Notes'} className="w-full border rounded p-2 text-sm"/><div className="flex flex-wrap gap-2">{dispositions.map(([v,l])=><label key={v} className="text-xs border rounded-full px-2 py-1"><input className="mr-1" type="checkbox" checked={(f.dispositions||[]).includes(v)} onChange={e=>updateFinding(f,{dispositions:e.target.checked?[...(f.dispositions||[]),v]:(f.dispositions||[]).filter(x=>x!==v)})}/>{l}</label>)}</div><div className="flex justify-end"><button disabled={saving||!(f.dispositions||[]).length} onClick={()=>routeFinding(f)} className="text-xs px-3 py-1.5 rounded-lg bg-blue-600 text-white disabled:opacity-40">{f.routed_at?'Update Routing':'Route Follow-Up'}</button></div></div>)}
   <button onClick={addFinding} className="text-sm text-blue-600 flex gap-1 items-center"><Plus className="w-4 h-4"/>Add finding</button>
  </fieldset>
  <fieldset disabled={readOnly} className="rounded-xl border p-4 space-y-3"><div className="flex justify-between gap-3"><div><h4 className="font-semibold">Sales Lead</h4><p className="text-xs text-gray-500 mt-1">Leave this open during the visit. Type or use voice-to-text to capture anything the customer may want to add, change, upgrade, or make easier to use. MJV creates the Lead automatically when the VIP visit is completed.</p></div><label className="text-xs flex gap-1.5"><input type="checkbox" checked={visit.no_opportunities_identified} onChange={e=>{if(e.target.checked&&leadDraft.trim()){alert('Clear the sales lead notes before selecting No Sales Lead Identified.');return;}patch({no_opportunities_identified:e.target.checked})}}/>No Sales Lead Identified</label></div>
   {!visit.no_opportunities_identified&&<div className="space-y-2"><textarea value={leadDraft} onChange={e=>{setLeadDraft(e.target.value);setLeadDraftDirty(true);}} onBlur={()=>{if(leadDraftDirty)void saveSalesLead();}} placeholder="Type or dictate what the customer is interested in…" className="w-full min-h-44 border rounded-xl p-3 text-base sm:text-sm"/><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={cleanSalesLead} disabled={cleaningLead||!leadDraft.trim()} className="inline-flex h-11 w-11 items-center justify-center rounded-lg border text-gray-600 hover:bg-gray-50 disabled:opacity-50 touch-manipulation" title="Clean up with AI" aria-label="Clean up sales lead notes with AI">{cleaningLead?<Loader className="w-5 h-5 animate-spin"/>:<Sparkles className="w-5 h-5"/>}</button><span className="text-xs text-gray-500">AI rewrites the text in place. Review or edit it before completing the visit. Relevant photos stay in Work Order Photos.</span></div></div>}
  </fieldset>
  <fieldset disabled={readOnly} className="rounded-xl border p-4"><h4 className="font-semibold mb-3">Review & Complete</h4><div className="flex flex-wrap gap-4"><label className="text-sm flex gap-2"><input type="checkbox" checked={visit.customer_not_present} onChange={e=>patch({customer_not_present:e.target.checked})}/>Customer Not Present</label>{!visit.customer_not_present&&<label className="text-sm flex gap-2"><input type="checkbox" checked={!!visit.customer_acknowledged_at} onChange={e=>patch({customer_acknowledged_at:e.target.checked?new Date().toISOString():null})}/>Customer acknowledgment captured</label>}</div>{!readOnly&&missing.length>0&&<div className="mt-3 flex gap-2 text-sm text-amber-700"><AlertCircle className="w-4 h-4 mt-0.5"/>Still required: {missing.join(', ')}</div>}</fieldset>
  {saving&&<p className="text-xs text-gray-400">Saving…</p>}
 </div>;
}
