import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {securityPaymentRequest} from '../../lib/securityOnboarding';
import SecurityPaymentEnrollment from '../Portal/SecurityPaymentEnrollment';
export function ActiveAutopayMethodEditor({contractId,organizationId,onUpdated}:{contractId:string;organizationId:string;onUpdated?:()=>void}) {
 const [allowed,setAllowed]=useState(false);const [open,setOpen]=useState(false);const [methodId,setMethodId]=useState('');const [reason,setReason]=useState('');const [authorized,setAuthorized]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{let live=true;void Promise.all([supabase.rpc('security_staff_access',{p_org:organizationId,p_manage:true}),supabase.from('security_contracts').select('status,security_billing_mode,security_payment_method_id,autopay_revoked_at').eq('id',contractId).eq('organization_id',organizationId).single()]).then(([access,c])=>{if(!live)return;setAllowed(!access.error&&!c.error&&access.data===true&&c.data?.status==='active'&&c.data.security_billing_mode==='autopay'&&!c.data.autopay_revoked_at);setMethodId(c.data?.security_payment_method_id||'');});return()=>{live=false;};},[contractId,organizationId]);
 async function save(){setBusy(true);try{await securityPaymentRequest('verify',contractId,'',{methodId});const {error}=await supabase.rpc('replace_security_autopay_method',{p_contract:contractId,p_method:methodId,p_reason:reason,p_authorized:authorized});if(error)throw new Error(error.message);setOpen(false);setReason('');setAuthorized(false);setMessage('Payment method updated with an audit record. Review any declined payment separately before scheduling a retry.');onUpdated?.();}catch(e){setMessage(e instanceof Error?e.message:'Payment method could not be updated');}finally{setBusy(false);}}
 if(!allowed)return null;
 return <div className="space-y-3"><button type="button" className="border rounded px-3 py-2 text-blue-700" onClick={()=>setOpen(!open)}>Update AutoPay payment method</button>{open&&<div className="border rounded-lg p-4 space-y-3"><SecurityPaymentEnrollment contractId={contractId} token="" selectedId={methodId} onSelect={m=>{setMethodId(m.id);setAuthorized(false);}}/><label className="flex gap-2"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/>Customer authorized this replacement for the existing AutoPay agreement.</label><label className="block">Authorization and change note<input className="border rounded p-2 w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" className="bg-blue-700 text-white rounded px-3 py-2" disabled={busy||!methodId||!authorized||reason.trim().length<10} onClick={()=>void save()}>{busy?'Saving…':'Save payment method'}</button></div>}{message&&<p role="status">{message}</p>}</div>;
}
