import {useCallback,useEffect,useState} from 'react';
import {AlertTriangle,RefreshCw} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {useAuth} from '../../contexts/AuthContext';
interface Delivery {id:string;audience:string;state:string;attempts:number;last_error:string|null;reminder:number}
interface BillingAlert {id:string;kind:string;cycle_id:string|null;contract_id:string;title:string;detail:string;created_at:string;acknowledged_at:string|null;security_payment_alert_deliveries:Delivery[]}
export function PaymentAlertsPanel({contractId,onOpenContract}:{contractId?:string;onOpenContract?:(id:string)=>void}) {
 const {profile}=useAuth();const [alerts,setAlerts]=useState<BillingAlert[]>([]);const [health,setHealth]=useState<string|null>(null);
 const [reviewing,setReviewing]=useState<string|null>(null);const [reviewReason,setReviewReason]=useState('');const [reconciled,setReconciled]=useState(false);
 const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [staffEmail,setStaffEmail]=useState('');const [fallbackEmail,setFallbackEmail]=useState('');const [emailDraft,setEmailDraft]=useState('');const [editingEmail,setEditingEmail]=useState(false);
 const reload=useCallback(async()=>{
  if(!profile?.organization_id)return;
  try {
   let query=supabase.from('security_payment_alerts').select('id,kind,cycle_id,contract_id,title,detail,created_at,acknowledged_at,security_payment_alert_deliveries(id,audience,state,attempts,last_error,reminder)').eq('organization_id',profile.organization_id).is('resolved_at',null).order('created_at',{ascending:false}).limit(100);
   if(contractId)query=query.eq('contract_id',contractId);
   const [issues,status,settings]=await Promise.all([query,supabase.from('security_payment_alert_health').select('last_scan_at').eq('organization_id',profile.organization_id).maybeSingle(),supabase.from('company_settings').select('billing_alert_email,company_email').eq('organization_id',profile.organization_id).maybeSingle()]);
   if(issues.error||status.error||settings.error)throw new Error(issues.error?.message||status.error?.message||settings.error?.message);
   setAlerts((issues.data||[]) as BillingAlert[]);setHealth(status.data?.last_scan_at||null);setStaffEmail(settings.data?.billing_alert_email||'');setFallbackEmail(settings.data?.company_email||'');setError('');
  }catch(e){setError(e instanceof Error?e.message:'Payment alerts could not be loaded');}finally{setLoading(false);}
 },[contractId,profile?.organization_id]);
 useEffect(()=>{void reload();const timer=setInterval(()=>void reload(),60000);return()=>clearInterval(timer);},[reload]);
 async function acknowledge(id:string){const {error}=await supabase.rpc('acknowledge_security_payment_alert',{p_id:id});if(error)setError(error.message);else await reload();}
 return <section className="no-print bg-white text-gray-900 border rounded-xl p-4 mb-5 space-y-3">
  <div className="flex items-center justify-between"><h2 className="font-semibold flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-600"/>Payment alerts</h2><button type="button" onClick={()=>void reload()} className="border rounded p-2" aria-label="Refresh payment alerts"><RefreshCw className="w-4 h-4"/></button></div>
  <p className="text-sm text-gray-600">Monitoring AutoPay failures and expiring methods. Staff email: {staffEmail||fallbackEmail||'Needs configuration'}. Acknowledging an alert does not resolve billing or stop reminders.</p>
  {!contractId && ['admin','finance'].includes(profile?.role||'') && <div className="flex flex-wrap gap-2 items-center">{editingEmail ? <><input type="email" aria-label="Billing alert email" className="border rounded p-2" value={emailDraft} onChange={e=>setEmailDraft(e.target.value)} placeholder={fallbackEmail||'billing@example.com'}/><button type="button" className="border rounded px-3 py-2" onClick={async()=>{const {error}=await supabase.rpc('set_billing_alert_email',{p_email:emailDraft});if(error)setError(error.message);else {setEditingEmail(false);await reload();}}}>Save alert recipient</button><button type="button" className="border rounded px-3 py-2" onClick={()=>{setEditingEmail(false);}}>Cancel</button></>:<button type="button" className="border rounded px-3 py-2 text-sm" onClick={()=>{setEmailDraft(staffEmail);setEditingEmail(true);}}>Set staff alert email</button>}</div>}
  {reviewing&&<div className="border rounded p-3 space-y-2"><p>Reconcile the bank return, invoice balance, QuickBooks accounting and any affected commissions before recording this review.</p><input aria-label="Return reconciliation evidence" className="border rounded p-2 w-full" placeholder="Record the reconciliation evidence" value={reviewReason} onChange={e=>setReviewReason(e.target.value)}/><label className="flex gap-2"><input type="checkbox" checked={reconciled} onChange={e=>setReconciled(e.target.checked)}/>I have reconciled the returned payment and affected records.</label><button type="button" className="border rounded px-3 py-2" disabled={!reconciled||reviewReason.trim().length<20} onClick={async()=>{const {error}=await supabase.rpc('review_security_payment_return',{p_cycle:reviewing,p_reason:reviewReason,p_reconciled:reconciled});if(error)setError(error.message);else{setReviewing(null);setReviewReason('');setReconciled(false);await reload();}}}>Record reconciliation</button><button type="button" className="border rounded px-3 py-2 ml-2" onClick={()=>setReviewing(null)}>Cancel</button></div>}
  {error?<p role="alert" className="text-red-700">{error}</p>:<>
   {(!health||Date.now()-Date.parse(health)>3600000) && <p role="alert" className="text-amber-800">Alert checks need attention: {health?`last completed ${new Date(health).toLocaleString()}`:'no completed scan recorded'}. Verify the scheduled worker before relying on notifications.</p>}
   {loading?<p>Loading payment alerts…</p>:alerts.length===0?<p className="text-sm">No open payment alerts.</p>:alerts.map(a=><article key={a.id} className="border rounded-lg p-3 space-y-2"><h3 className="font-medium">{a.title}</h3><p className="text-sm">{a.detail}</p><p className="text-xs text-gray-500">Opened {new Date(a.created_at).toLocaleString()}{a.acknowledged_at?' · Acknowledged':''}</p><ul className="text-xs space-y-1">{[...a.security_payment_alert_deliveries].sort((x,y)=>y.reminder-x.reminder).slice(0,6).map(d=><li key={d.id}>{d.audience==='customer'?'Customer':'Staff'} email{d.reminder>0?` · day ${d.reminder} reminder`:''}: {d.state==='sent'?'Accepted by email provider':d.state} · {d.attempts} attempt(s){d.last_error&&<span className="text-red-700"> — {d.last_error}</span>}</li>)}</ul><div className="flex flex-wrap gap-2">{a.kind==='payment_returned'&&a.cycle_id&&<button type="button" className="border rounded px-3 py-1" onClick={()=>{setReviewing(a.cycle_id);setReviewReason('');setReconciled(false);}}>Review returned payment</button>}{onOpenContract&&<button type="button" className="border rounded px-3 py-1 text-blue-700" onClick={()=>onOpenContract(a.contract_id)}>Review agreement</button>}{!a.acknowledged_at&&<button type="button" className="border rounded px-3 py-1" onClick={()=>void acknowledge(a.id)}>Acknowledge</button>}</div></article>)}
   {alerts.length===100&&<p className="text-sm">Showing the 100 newest open alerts. Open an agreement to review its alerts.</p>}
  </>}
 </section>;
}
