import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('test.uid',true),'')::uuid$$;
CREATE TABLE profiles(id uuid PRIMARY KEY, organization_id uuid, role text, is_active boolean);
CREATE TABLE company_settings(organization_id uuid, company_name text,company_logo_url text,website text,updated_at timestamptz, private_secret text);
CREATE TABLE business_cards(user_id uuid,slug text,is_active boolean);
INSERT INTO profiles VALUES('${id(1)}','${id(10)}','admin',true),('${id(2)}','${id(20)}','admin',true),('${id(3)}','${id(10)}','tech',true),('${id(4)}','${id(10)}','admin',false);
INSERT INTO company_settings VALUES('${id(10)}','Electronic Life','logo-a','website-a',now(),'secret-a'),('${id(20)}','Other Dealer','logo-b','website-b',now(),'secret-b');
INSERT INTO business_cards VALUES('${id(1)}','josh',true),('${id(2)}','other',true),('${id(1)}','inactive',false);
`);
await db.exec(await readFile('supabase/migrations/20261003162307_business_card_artwork.sql','utf8'));
async function as(user, role, sql) {
  await db.exec(`RESET ROLE; SELECT set_config('test.uid','${user}',false); SET ROLE ${role};`);
  return db.query(sql);
}
const branding = (await as('', 'anon', "SELECT get_business_card_branding('josh') AS brand")).rows[0].brand;
assert.equal(branding.company_name, 'Electronic Life');
assert.equal(branding.organization_id,id(10));
assert.equal(Object.keys(branding).length,5);
assert.ok(!JSON.stringify(branding).includes('secret'));
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('inactive') AS brand")).rows[0].brand,null);
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('missing') AS brand")).rows[0].brand,null);
assert.equal((await as(id(2), 'authenticated', "SELECT get_business_card_branding('inactive') AS brand")).rows[0].brand,null);
assert.equal((await as(id(1), 'authenticated', "SELECT get_business_card_branding('inactive') AS brand")).rows[0].brand.company_name,'Electronic Life');
await assert.rejects(() => as('', 'anon', "SELECT set_business_card_banner('https://example.com/art.png')"));
for(const actor of [id(3), id(4)]) await assert.rejects(() => as(actor,'authenticated',"SELECT set_business_card_banner('https://example.com/art.png')"));
await as(id(1),'authenticated',"SELECT set_business_card_banner('https://example.com/art.png')");
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('josh') AS brand")).rows[0].brand.business_card_banner_url,'https://example.com/art.png');
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('other') AS brand")).rows[0].brand.business_card_banner_url,null);
await assert.rejects(() => as(id(1),'authenticated',"SELECT set_business_card_banner('javascript:alert(1)')"));
await as(id(1),'authenticated',"SELECT set_business_card_banner('')");
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('josh') AS brand")).rows[0].brand.business_card_banner_url,'');
await as(id(1),'authenticated',"SELECT set_business_card_banner(NULL)");
assert.equal((await as('', 'anon', "SELECT get_business_card_branding('josh') AS brand")).rows[0].brand.business_card_banner_url,null);
await db.close();
console.log('Public branding, inactive cards, restricted fields, admin authorization, tenant isolation, removal and reset passed.');
