import { useEffect, useState } from 'react';
import { Eye, RefreshCw } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { proposalChoices, isProposalChoice } from '../../../supabase/functions/_shared/proposalCheckOptions';
interface EmailRecord {id:string;recipient_name:string;recipient_email:string;sender_name:string;reply_to:string;subject:string;variant:string;created_at:string;sent_at:string|null;opened_at:string|null;last_opened_at:string|null;status:string;proposal_id:string|null;click_count:number;interaction_count:number;message_count:number;latest_choice:string|null;confirmed_choice:string|null;last_clicked_at:string|null}
interface Activity {id:string;kind:string;choice:string;step:string|null;message:string|null;suspected_automated:boolean;created_at:string}
const date=(v:string|null)=>v?new Date(v).toLocaleString():'—';
const label=(v:string|null)=>isProposalChoice(v)?proposalChoices[v].label:'—';
export default function ProposalCheckHistory({refreshKey}:{refreshKey:number}) {
 const [records,setRecords]=useState<EmailRecord[]>([]);const [page,setPage]=useState(0);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [refresh,setRefresh]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [totals,setTotals]=useState({sent:0,opened:0,clicked:0,messages:0});const [preview,setPreview]=useState<{subject:string;html:string}|null>(null);const [timeline,setTimeline]=useState<{row:EmailRecord;events:Activity[];page:number;more:boolean}|null>(null);
 useEffect(()=>{const timer=setTimeout(()=>{setPage(0);setQuery(search)},250);return()=>clearTimeout(timer)},[search]);
 useEffect(()=>{let current=true;setLoading(true);setError('');let request=supabase.from('proposal_check_reporting').select('*').order('created_at',{ascending:false}).range(page*50,page*50+49);const term=query.replace(/[^a-zA-Z0-9@. +\-]/g,'').slice(0,100).trim();if(term)request=request.or(`recipient_name.ilike.%${term}%,recipient_email.ilike.%${term}%`);
 if(isProposalChoice(filter))request=request.or(`confirmed_choice.eq.${filter},and(confirmed_choice.is.null,latest_choice.eq.${filter})`);
 if(filter==='clicked_no_message')request=request.gt('click_count',0).eq('message_count',0);
 if(filter==='message')request=request.gt('message_count',0);if(filter==='opened')request=request.not('opened_at','is',null);
 void request.then(({data,error})=>{if(!current)return;if(error){setError('History could not load. Please refresh.');setRecords([])}else setRecords((data||[]) as EmailRecord[]);setLoading(false)});
 const counts=[supabase.from('proposal_check_reporting').select('id',{count:'exact',head:true}).eq('status','sent'),supabase.from('proposal_check_reporting').select('id',{count:'exact',head:true}).not('opened_at','is',null),supabase.from('proposal_check_reporting').select('id',{count:'exact',head:true}).gt('click_count',0),supabase.from('proposal_check_reporting').select('id',{count:'exact',head:true}).gt('message_count',0)];
 void Promise.all(counts).then(results=>{if(current){if(results.some(r=>r.error))setError('Some reporting totals could not load. Please refresh.');else setTotals({sent:results[0].count||0,opened:results[1].count||0,clicked:results[2].count||0,messages:results[3].count||0})}});return()=>{current=false};},[page,query,filter,refresh,refreshKey]);
 useEffect(()=>{if(!preview&&!timeline)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPreview(null);setTimeline(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[preview,timeline]);
 async function showEmail(row:EmailRecord){const {data,error}=await supabase.from('proposal_check_emails').select('email_html').eq('id',row.id).single();if(error)setError('Saved email could not load.');else setPreview({subject:row.subject,html:data.email_html})}
 async function showTimeline(row:EmailRecord,eventPage=0){const {data,error}=await supabase.from('proposal_check_events').select('id,kind,choice,step,message,suspected_automated,created_at').eq('email_id',row.id).order('created_at',{ascending:false}).order('id',{ascending:false}).range(eventPage*50,eventPage*50+49);if(error)setError('Activity could not load.');else setTimeline({row,events:(data||[]) as Activity[],page:eventPage,more:data?.length===50})}
 return <section aria-label="Proposal Check Send History" className="space-y-4 rounded-xl border border-gray-700 bg-gray-800 p-4 sm:p-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold text-white">Proposal Check Reporting</h2><button disabled={loading} onClick={()=>setRefresh(v=>v+1)} className="flex min-h-11 items-center gap-2 text-gray-200"><RefreshCw size={18}/>Refresh</button></div>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries({Sent:totals.sent,'Open detected':totals.opened,'Link visits':totals.clicked,'Message received':totals.messages}).map(([name,value])=><div key={name} className="rounded-lg bg-gray-900 p-3"><p className="text-2xl font-bold text-white">{value}</p><p className="text-sm text-gray-400">{name}</p></div>)}</div><p className="text-xs text-gray-400">Totals count emails across all history you can access.</p>
  <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-gray-300">Search customer or email<input value={search} onChange={e=>setSearch(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 p-3 text-white"/></label><label className="text-sm text-gray-300">Response filter<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 p-3 text-white"><option value="all">All</option>{Object.entries(proposalChoices).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}<option value="clicked_no_message">Clicked, no message</option><option value="opened">Open detected</option><option value="message">Message received</option></select></label></div>
  {error&&<p role="alert" className="text-red-300">{error}</p>}
  {loading?<p role="status" className="text-gray-400">Loading history…</p>:!records.length?<p className="text-gray-400">No emails match.</p>:records.map(row=><article key={row.id} className="space-y-3 rounded-lg border border-gray-700 bg-gray-900 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold text-white">{row.recipient_name}</h3><p className="break-all text-sm text-gray-400">{row.recipient_email}</p></div><span className="text-sm text-cyan-300">{row.status==='sent'?'Sent':row.status==='failed'?'Send failed':'Send pending'}</span></div><p className="font-medium text-gray-200">{row.subject}</p><p className="text-sm text-cyan-300">{row.confirmed_choice?`Response page selection: ${label(row.confirmed_choice)}`:row.latest_choice?`Email link visited: ${label(row.latest_choice)} (unconfirmed)`:'No button activity detected'} · {row.message_count?`${row.message_count} message(s) received`:'No message submitted'}</p><dl className="grid gap-2 text-sm text-gray-400 sm:grid-cols-2"><div>Sender: {row.sender_name} · {row.variant==='owner'?'Owner':'Salesperson'}</div><div>Sent: {date(row.sent_at||row.created_at)}</div><div>First open detected: {date(row.opened_at)}</div><div>Latest open detected: {date(row.last_opened_at||row.opened_at)}</div><div>Latest link visit: {date(row.last_clicked_at)}</div><div>{row.click_count} link visit(s) · {row.interaction_count} page interaction(s)</div><div className="break-all">Replies to: {row.reply_to}</div></dl><div className="flex flex-wrap gap-4"><button onClick={()=>void showTimeline(row)} className="min-h-11 text-sm text-cyan-300">View activity & messages</button><button onClick={()=>void showEmail(row)} className="flex min-h-11 items-center gap-2 text-sm text-cyan-300"><Eye size={16}/>View Sent Email</button>{row.proposal_id&&<a className="flex min-h-11 items-center text-sm text-cyan-300" href={`/?tab=proposals&proposalId=${row.proposal_id}`}>Linked Proposal</a>}</div></article>)}
  <div className="flex justify-between text-sm text-gray-300"><button disabled={!page||loading} onClick={()=>setPage(v=>v-1)} className="min-h-11 disabled:opacity-40">Previous</button><span>Page {page+1}</span><button disabled={records.length<50||loading} onClick={()=>setPage(v=>v+1)} className="min-h-11 disabled:opacity-40">Next</button></div>
  <p className="text-xs text-gray-400">Open detected means a tracking image loaded, which privacy tools may do automatically. Link visits may include security scanners; response-page interactions and submitted messages are shown separately. No signal does not prove the email was unread. Previews do not record engagement. Tracking applies to new emails; older messages retain their available history.</p>
  {(preview||timeline)&&<div role="dialog" aria-modal="true" aria-label={timeline?'Proposal check activity':'Saved proposal check email'} className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3"><div className="flex max-h-[90dvh] w-full max-w-3xl flex-col overflow-hidden rounded-xl border border-gray-600 bg-gray-900"><div className="flex shrink-0 items-center justify-between gap-3 p-4"><h3 className="font-semibold text-white">{timeline?timeline.row.recipient_name:preview?.subject}</h3><button autoFocus onClick={()=>{setTimeline(null);setPreview(null)}} className="min-h-11 px-3 text-gray-200">Close</button></div>{preview?<iframe title="Saved sent email" sandbox="" referrerPolicy="no-referrer" srcDoc={preview.html} className="h-[650px] max-h-[75vh] w-full bg-white"/>:<div className="overflow-auto p-4 text-gray-200">{!timeline?.events.length?<p>No activity recorded.</p>:timeline.events.map(event=><div key={event.id} className="mb-3 space-y-2 rounded-lg border border-gray-700 p-3"><p className="font-semibold">{event.kind==='message'?'Message submitted':event.kind==='interaction'?'Response page interaction':'Email link visited'}: {label(event.choice)}</p>{event.step&&<p>{event.step}</p>}{event.message&&<p className="whitespace-pre-wrap break-words">{event.message}</p>}<p className="text-xs text-gray-400">{date(event.created_at)}{event.kind==='link_visit'&&(event.suspected_automated?' · Suspected automated visit':' · Unconfirmed link activity')}</p></div>)}{timeline&&<div className="flex justify-between"><button disabled={!timeline.page} className="min-h-11 disabled:opacity-40" onClick={()=>void showTimeline(timeline.row,timeline.page-1)}>Newer activity</button><button disabled={!timeline.more} className="min-h-11 disabled:opacity-40" onClick={()=>void showTimeline(timeline.row,timeline.page+1)}>Older activity</button></div>}</div>}</div></div>}
 </section>;
}
