import { build } from 'esbuild';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const directory = await mkdtemp(join(tmpdir(), 'mjv-proposals-mobile-'));
const fixture = `
export const profile={id:'rep',organization_id:'org',role:'sales',proposal_visibility_scope:'own'};
export const useAuth=()=>({profile,loading:false});
window.actions=[];
const records=Array.from({length:8},(_,i)=>({id:'p'+i,proposal_number:'PRO-01-'+i,title:'Project '+i+' with a long title to verify truncation',status:i===1?'expired':'sent',total:23371.93,created_at:'2026-09-08T12:00:00Z',sent_at:'2026-09-08T12:00:00Z',expires_at:'2026-10-08T12:00:00Z',contacts:{id:'c'+i,full_name:'Customer '+i+' Long Lastname'},profiles:{full_name:'Josh Gorrell'},revision_count:1,is_portal_visible:true}));
const pending={...records[0],id:location.search.includes('overlap')?'p0':'deposit',status:'approved',title:'Pending deposit project',contacts:{id:'cd',full_name:'Julio Eglesias'},require_deposit:true,deposit_paid:false,deposit_amount_due:1000,sales_order_id:'so'};
export const supabase={from(table){let single=false;let search='';const result=()=>{let data=table==='proposals_with_revision_count'?(search?[]:records):table==='proposals'?[pending]:table==='sales_orders'?[{id:'so',proposal_id:pending.id}]:table==='profiles'?[{proposals_hide_approved:true}]:[];return Promise.resolve({data:single?data[0]:data,error:null,count:data.length})};const q=new Proxy({},{get(_,key){if(key==='then')return(a,b)=>result().then(a,b);if(key==='single'||key==='maybeSingle')return()=>{single=true;return result()};if(key==='or')return value=>{if(value.includes('ilike'))search=value;return q};return()=>q}});return q}};
`;
const source=`import React from 'react';import {createRoot} from 'react-dom/client';import ProposalsList from './src/components/Proposals/ProposalsList';createRoot(document.getElementById('root')).render(<><header style={{height:56}}>Electronic Life</header><nav style={{height:40}}>Pipeline · Production · Dispatch</nav><main className="px-3 py-3"><ProposalsList onSelectProposal={id=>window.actions.push(['proposal',id])} onCreateNew={()=>window.actions.push(['new'])} onSelectSalesOrder={id=>window.actions.push(['order',id])} onNavigateToSalesOrders={()=>window.actions.push(['orders'])}/></main></>);`;
let browser;
const server=createServer(async(req,res)=>{try{const file=req.url.startsWith('/app.js')?'app.js':req.url.startsWith('/style.css')?'style.css':'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(join(directory,file)));}catch{res.writeHead(404);res.end();}});
try {
  await build({stdin:{contents:source,resolveDir:process.cwd(),loader:'tsx'},bundle:true,format:'iife',jsx:'automatic',outfile:join(directory,'app.js'),plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/lib\/supabase$|contexts\/AuthContext$/},()=>({path:'fixture',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:fixture}));}}]});
  const css=(await readdir('dist/assets')).find(p=>p.startsWith('index-')&&p.endsWith('.css'));
  await writeFile(join(directory,'style.css'),await readFile('dist/assets/'+css));
  await writeFile(join(directory,'index.html'),'<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script src="app.js"></script></body></html>');
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH || undefined,args:['--no-sandbox']});
  const page=await browser.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  for(const size of [{width:390,height:760,min:5},{width:430,height:840,min:6},{width:375,height:667,min:4}]){
    await page.setViewportSize(size);await page.goto('http://127.0.0.1:'+server.address().port);
    const first=page.locator('#proposal-row-p0 > .sm\\:hidden > button');await first.waitFor();
    const visible=await page.locator('[id^="proposal-row-"]').evaluateAll(rows=>rows.filter(r=>{const b=r.getBoundingClientRect();return b.height>0&&b.bottom<=innerHeight}).length);
    assert.ok(visible>=size.min,JSON.stringify({size,visible}));
    if(process.env.PROPOSALS_SCREENSHOT_DIR)await page.screenshot({path:join(process.env.PROPOSALS_SCREENSHOT_DIR,`proposals-${size.width}.png`)});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.equal(await page.getByRole('button',{name:'New',exact:true}).count(),1);
    assert.equal(await page.locator('select').filter({visible:true}).count(),0);
    await first.click();assert.equal(await first.getAttribute('aria-expanded'),'true');
    assert.equal(await page.evaluate(()=>window.actions.length),0);
    assert.ok((await page.locator('#proposal-details-p0').innerText()).includes('$23,371.93'));
    await page.getByRole('button',{name:'Proposal actions',exact:true}).click();
    assert.equal(await page.getByRole('button',{name:'Duplicate',exact:true}).isVisible(),true);
    const second=page.locator('#proposal-row-p1 > .sm\\:hidden > button');await second.click();
    assert.equal(await first.getAttribute('aria-expanded'),'false');assert.equal(await second.getAttribute('aria-expanded'),'true');
    await second.click();assert.equal(await second.getAttribute('aria-expanded'),'false');
    await second.focus();await page.keyboard.press('Enter');assert.equal(await second.getAttribute('aria-expanded'),'true');
    await page.getByRole('button',{name:'Open Proposal',exact:true}).click();
    assert.deepEqual(await page.evaluate(()=>window.actions.at(-1)),['proposal','p1']);
    await page.getByRole('button',{name:'1 Awaiting Deposit',exact:true}).click();
    await page.getByRole('button',{name:'Open Sales Order',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.actions.at(-1)),['order','so']);
    assert.equal(await page.locator('#proposal-row-deposit').count(),1);
    await page.getByRole('button',{name:'Proposal tools',exact:true}).click();await page.getByRole('button',{name:'Sales Orders',exact:true}).click();
    assert.deepEqual(await page.evaluate(()=>window.actions.at(-1)),['orders']);
    await page.getByRole('button',{name:'Filter proposals',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Filter Proposals',exact:true}).isVisible(),true);
    await page.getByRole('button',{name:'Filter proposals',exact:true}).click();
    await page.getByRole('button',{name:'New',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.actions.at(-1)),['new']);
    console.log(size.width+'x'+size.height+': '+visible+' collapsed rows visible; expansion and actions pass');
  }
  await page.goto('http://127.0.0.1:'+server.address().port+'?overlap');
  await page.locator('#proposal-row-p0').waitFor();
  assert.equal(await page.locator('#proposal-row-p0').count(),1);
  await page.getByRole('button',{name:'1 Awaiting Deposit',exact:true}).click();
  assert.equal(await page.locator('#proposal-details-p0').isVisible(),true);
  await page.getByRole('textbox',{name:'Search proposals',exact:true}).fill('no matches');
  await page.waitForFunction(()=>document.querySelectorAll('[id^="proposal-row-"]').length===1);
  assert.equal(await page.locator('#proposal-row-p0').count(),1);
  assert.equal(await page.locator('#proposal-details-p0').count(),0);
  console.log('Pending deposits deduplicated and accessible with empty search results');
  await page.setViewportSize({width:1280,height:900});await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#proposal-row-p0').waitFor();
  assert.equal(await page.locator('#proposal-row-deposit').isVisible(),false);
  assert.equal(await page.getByRole('button',{name:'New Proposal',exact:true}).isVisible(),true);
  assert.equal(await page.locator('select').filter({visible:true}).count(),1);
  assert.equal(await page.locator('#proposal-row-p0 > .sm\\:hidden > button').isVisible(),false);
  assert.deepEqual(errors,[]);console.log('Desktop presentation preserved; no browser errors');
} finally {await browser?.close();server.close();await rm(directory,{recursive:true,force:true});}
