import assert from 'node:assert/strict';import {build} from 'esbuild';import {chromium} from 'playwright';import{mkdtemp,readFile,readdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{createServer}from'node:http';import{fixture}from'./fixture.mjs';
const directory=await mkdtemp(join(tmpdir(),'mjv-pm-'));
const server=createServer(async(req,res)=>{const file=req.url.startsWith('/app.js')?'app.js':req.url.startsWith('/style.css')?'style.css':'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(join(directory,file)));});let browser;
try{
 await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import ProjectsView from './src/components/Projects/ProjectsView';import ProjectTasksList from './src/components/Projects/ProjectTasksList';createRoot(document.getElementById('root')).render(location.search.includes('taskFixture')?<ProjectTasksList projectId="p1" canEdit/>:<ProjectsView/>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,format:'iife',jsx:'automatic',outfile:join(directory,'app.js'),plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/timezoneUtils$/},()=>({path:'timezone',namespace:'timezone'}));b.onLoad({filter:/.*/,namespace:'timezone'},()=>({contents:'export const getOrganizationTimezone=async()=>"America/Chicago"',loader:'js'}));b.onResolve({filter:/supabase$|contexts\/AuthContext$/},()=>({path:'fixture',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:fixture,loader:'js',resolveDir:process.cwd()}));b.onResolve({filter:/\.\/ProjectDetail$/},()=>({path:'detail',namespace:'detail'}));b.onLoad({filter:/.*/,namespace:'detail'},()=>({contents:'export default function Detail(){return null}',loader:'js'}));b.onResolve({filter:/lib\/useJobDraft$/},()=>({path:'draft',namespace:'draft'}));b.onLoad({filter:/.*/,namespace:'draft'},()=>({contents:"import{useState}from'react';export const useJobDraft=(_key)=>useState(null);",loader:'js',resolveDir:process.cwd()}));}}]});
 const css=(await readdir('dist/assets')).find(file=>file.startsWith('index-')&&file.endsWith('.css'));await writeFile(join(directory,'style.css'),Buffer.concat([await readFile('dist/assets/'+css),await readFile(join(directory,'app.css'))]));await writeFile(join(directory,'index.html'),'<html data-theme="light"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.css"></head><body><main style="padding:12px"><div id="root"></div></main><script src="app.js"></script></body></html>');
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));const url='http://127.0.0.1:'+server.address().port;
 for(const [width,height]of[[320,568],[375,667],[768,1024],[1280,720],[1920,1080],[960,540]]){
  await page.setViewportSize({width,height});await page.goto(url+'?tab=projects');await page.getByRole('link',{name:'Event Center',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No page overflow at '+width);
  assert.equal(await page.locator('.pm-card').count(),2);assert.equal(await page.locator('.pm-card').first().locator('.pm-identity strong').textContent(),'Alpha Customer');
  assert.ok((await page.locator('.pm-card').first().textContent()).includes('105% used'));assert.equal(await page.getByText('Private other tenant',{exact:true}).count(),0);
  assert.equal(await page.getByRole('link',{name:'Event Center',exact:true}).getAttribute('href'),'/?tab=sales_orders&openOrderId=so1&orderTab=project');
  for(const field of await page.locator('.pm-filters input,.pm-filters select,.pm-expand').all())assert.ok((await field.boundingBox()).height>=44,'Touch controls at least 44px');
  await page.getByRole('button',{name:'Show tasks and work orders for Event Center',exact:true}).click();await page.getByText('Finish installation',{exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'WO1 · Install equipment',exact:true}).getAttribute('href'),'/?tab=work_orders&workOrderId=w1');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Expanded details fit '+width);await page.screenshot({path:'/tmp/mjv-projects-'+width+'.png'});
 }
 await page.getByLabel('Projects',{exact:true}).selectOption('mine');assert.equal(await page.locator('.pm-card').count(),1);await page.getByLabel('Projects',{exact:true}).selectOption('unassigned');assert.equal(await page.locator('.pm-card').count(),1);assert.equal(await page.locator('.pm-identity strong').textContent(),'Beta Customer');await page.getByLabel('Projects',{exact:true}).selectOption('all');
 await page.getByLabel('Search customer or project',{exact:true}).fill('Beta');assert.equal(await page.locator('.pm-card').count(),1);assert.ok(new URL(page.url()).searchParams.get('projectSearch')==='Beta');await page.reload();await page.getByRole('link',{name:'Whole-house installation with a long project name',exact:true}).waitFor();assert.equal(await page.locator('.pm-card').count(),1);await page.getByLabel('Search customer or project',{exact:true}).fill('');
 await page.evaluate(()=>{window.fixtureData.project_tasks.push({id:'new',organization_id:'org',project_id:'p1',title:'New follow-up',status:'open'});});await page.getByRole('button',{name:'Refresh projects',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.pm-card').textContent.includes('3 open'));
 await page.evaluate(()=>window.failProjects=true);await page.getByRole('button',{name:'Refresh projects',exact:true}).click();await page.getByRole('alert').waitFor();await page.evaluate(()=>window.failProjects=false);await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByRole('alert').waitFor({state:'detached'});
 await page.goto(url+'?taskFixture=1');await page.getByText('Finish installation',{exact:true}).waitFor();assert.equal(await page.getByRole('alert').count(),0,'Legacy task schema can load without missing activity table');await page.locator('details').filter({hasText:'Finish installation'}).locator('summary').click();page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Complete entire task',exact:true}).first().click();await page.waitForFunction(()=>window.lastTaskUpdate);assert.equal(await page.evaluate(()=>Object.hasOwn(window.lastTaskUpdate,'progress_status')),false,'Legacy status updates omit undeployed columns');
 assert.deepEqual(errors,[]);console.log('PASS: responsive customer-first projects, filters, rank, details, links, tenant scoping, refresh/retry, and legacy task compatibility.');
}finally{await browser?.close();server.close();await rm(directory,{recursive:true,force:true});}
