export const fixture = `
const profile={id:'pm',organization_id:'org',role:'project_manager'};export function useAuth(){return {profile,loading:false,user:{id:'pm'}}};
const day=(delta)=>{const date=new Date();date.setDate(date.getDate()+delta);return date.toISOString().slice(0,10)};
export const dataset={
 projects:[{id:'p1',organization_id:'org',contact:{company_name:'Alpha Customer'},name:'Event Center',project_number:'P1',status:'active',assigned_pm:'pm',office_id:'office',sales_order_id:'so1',target_completion_date:day(10),sales_order:{id:'so1',proposal_id:'prop1'}},{id:'p2',organization_id:'org',contact:{full_name:'Beta Customer'},name:'Whole-house installation with a long project name',project_number:'P2',status:'planning',assigned_pm:null,sales_order_id:'so2',sales_order:{id:'so2',proposal_id:'prop2'}},{id:'p3',organization_id:'org',contact:{full_name:'Closed Customer'},name:'Completed project',project_number:'P3',status:'closed',sales_order_id:'so3',sales_order:{id:'so3',proposal_id:'prop3'}},{id:'foreign',organization_id:'foreign',name:'Private other tenant',sales_order:{id:'foreign-order',proposal_id:'foreign-proposal'}}],
 proposal_line_items:[{id:'i1',organization_id:'org',proposal_id:'prop1',quantity:2,labor_hours:10},{id:'i2',organization_id:'org',proposal_id:'prop2',quantity:1,labor_hours:0}],change_orders:[],change_order_line_items:[],
 time_entries:[{id:'te1',organization_id:'org',project_id:'p1',work_order_id:'w1',labor_phase_id:'install',total_hours:20,clock_out:day(-1)+'T15:00:00Z',entry_date:day(-1),status:'approved'}],
 work_orders:[{id:'w1',organization_id:'org',project_id:'p1',title:'Install equipment',work_order_number:'WO1',status:'in_progress',assigned_to:'tech',scheduled_date:day(1),scheduled_start_time:'09:00',is_archived:false},{id:'w2',organization_id:'org',project_id:'p1',title:'Programming',work_order_number:'WO2',status:'pending',assigned_to:null,is_archived:false}],
 project_tasks:[{id:'t1',organization_id:'org',project_id:'p1',title:'Finish installation',status:'open',estimated_hours:2},{id:'t2',organization_id:'org',project_id:'p1',title:'Check programming',status:'open',estimated_hours:1}],
 labor_phases:[{id:'install',organization_id:'org',name:'Install'}],labor_phase_performance_mapping:[],profiles:[{id:'pm',organization_id:'org',full_name:'Project Manager'},{id:'tech',organization_id:'org',full_name:'Technician'}],company_offices:[{id:'office',organization_id:'org',name:'Topeka'}],work_order_options:[]};
window.fixtureData=dataset;window.projectQueries=[];window.failProjects=false;
export const supabase={from(table){let filters=[],bounds=null;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);window.projectQueries.push({table,k,v});return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},order(){return q},range(a,b){bounds=[a,b];return q},update(values){window.lastTaskUpdate=values;return q},insert(values){window.lastTaskInsert=values;return q},then(a,b){if(window.failProjects&&table==='projects')return Promise.resolve({data:null,error:{message:'Unable to load projects'}}).then(a,b);let data=(dataset[table]||[]).filter(r=>filters.every(f=>f(r)));if(bounds)data=data.slice(bounds[0],bounds[1]+1);return Promise.resolve({data,error:null}).then(a,b)}};return q}};
`;
