import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const org='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002',customer='20000000-0000-0000-0000-000000000001',a='30000000-0000-0000-0000-000000000001',b='30000000-0000-0000-0000-000000000002',part='40000000-0000-0000-0000-000000000001',product='50000000-0000-0000-0000-000000000001';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema private;
create function auth.jwt() returns jsonb language sql as $$select '{"role":"authenticated"}'::jsonb$$;
create function auth.uid() returns uuid language sql as $$select coalesce(nullif(current_setting('test.actor',true),''),'${org}')::uuid$$;
create function public.get_user_org_id() returns uuid language sql as $$select '${org}'::uuid$$;
create function public.can_view_all_org_invoices() returns boolean language sql as $$select auth.uid()='${org}'::uuid$$;
create table organizations(id uuid primary key);
insert into organizations values('${org}'),('${other}');
create table work_orders(id uuid primary key,organization_id uuid,contact_id uuid,project_id uuid,work_order_group_id uuid,status text,type text,is_billable boolean,actual_completion_date timestamptz,assigned_to uuid);
create table products(id uuid primary key,organization_id uuid);
insert into products values('${product}','${org}');
create table service_parts_used(id uuid primary key,work_order_id uuid);
create table time_entries(id uuid default gen_random_uuid(),work_order_id uuid,organization_id uuid,total_hours numeric,clock_out timestamptz,status text);
create table invoices(id uuid primary key default gen_random_uuid(),organization_id uuid,company_id uuid,contact_id uuid,project_id uuid,created_by uuid,invoice_date date,due_date date,status text,subtotal numeric,tax_amount numeric,total numeric,amount_paid numeric,amount_due numeric,notes text,tax_environment text,tax_project_type text,tax_rate numeric,payment_terms text,billing_name text,billing_address_line1 text,billing_address_line2 text,billing_city text,billing_state text,billing_zip text,portal_visible boolean default false);
create table invoice_line_items(id uuid default gen_random_uuid(),invoice_id uuid references invoices,organization_id uuid,description text,quantity numeric,unit_price numeric,amount numeric,item_type text,is_taxable boolean,product_id uuid,sku text,cost numeric,notes text,notes_visible_on_invoice boolean,sort_order int);
create table service_requests(id uuid,work_order_id uuid,organization_id uuid,billable_by text,billable_by_user_id uuid);
create table service_billing_queue(work_order_id uuid,organization_id uuid,contact_id uuid,service_request_id uuid,billable_by text,assigned_to_user_id uuid,completed_at timestamptz,billing_deadline timestamptz,status text default 'ready_for_billing',invoice_id uuid,invoiced_at timestamptz);
create function submit_invoice(p_id uuid) returns jsonb language plpgsql set search_path=public as $$begin if exists(select 1 from invoices where id=p_id and notes='reject') then return '{"success":false,"errors":["rejected"]}'::jsonb;end if;update invoices set status='submitted',portal_visible=true where id=p_id;return '{"success":true}'::jsonb;end$$;
insert into work_orders values('${a}','${org}','${customer}',null,'${org}','completed','service',true,now(),null),('${b}','${org}','${customer}',null,'${org}','completed','service',true,now(),null);
insert into service_parts_used values('${part}','${b}');
insert into time_entries(work_order_id,total_hours,clock_out,status) values('${a}',2,now(),'draft'),('${b}',2.13,now(),'submitted');`);
await db.exec(await readFile('supabase/migrations/20261006150553_work_order_invoice_closeout.sql','utf8'));
await db.exec(`create table company_settings(organization_id uuid,portal_invoices_enabled boolean);insert into company_settings values('${org}',true);create table quickbooks_settings(id uuid);create table profiles(id uuid primary key);insert into profiles values('${org}');
alter table invoices add column invoice_number text,add column tax_snapshot_id uuid,add column tax_jurisdiction_id uuid,add column jobsite_address text,add column jobsite_city text,add column jobsite_state text,add column jobsite_zip text,add column security_billing_cycle_id uuid;`);
const deliverySql=await readFile('supabase/migrations/20261006152705_invoice_portal_delivery.sql','utf8');
await db.exec(deliverySql.slice(0,deliverySql.indexOf('-- Reuse')));
await db.exec(await readFile('supabase/migrations/20261006153642_invoice_submission_unlock.sql','utf8'));
await db.exec('create trigger trg_prevent_post_submit_changes before update on invoices for each row execute function prevent_post_submit_field_changes()');
await db.exec(`create table contacts(id uuid primary key,organization_id uuid,portal_user_id uuid);insert into contacts values('${customer}','${org}','70000000-0000-0000-0000-000000000001');grant select on contacts to authenticated;alter table invoices enable row level security;create policy finance_test on invoices for all to authenticated using(organization_id=public.get_user_org_id() and public.can_view_all_org_invoices()) with check(organization_id=public.get_user_org_id() and public.can_view_all_org_invoices());`);
const baseline=await readFile('supabase/migrations/20260923134130_invoice_cutover_submit_void_rls_locking.sql','utf8');
const policyStart=baseline.indexOf('CREATE POLICY "Portal users can view their invoices"');
const policyEnd=baseline.indexOf('-- ============================================================',policyStart);
await db.exec(baseline.slice(policyStart,policyEnd));
await db.exec('grant usage on schema public,auth to authenticated;grant all on company_settings,organizations,profiles,work_orders,products,service_parts_used,time_entries,invoices,invoice_line_items,service_requests,service_billing_queue to authenticated;set role authenticated');

const header={invoice_date:'2026-10-06',due_date:'2026-10-06',tax_amount:10,tax_rate:.1};
const lines=[{description:'Service labor',quantity:4.25,unit_price:100,item_type:'labor'},{description:'Part',quantity:2,unit_price:100,cost:20,item_type:'material',source_part_id:part,product_id:product,notes:'internal',notes_visible_on_invoice:false}];
const save=async(request,opts={})=>(await db.query('select save_work_order_invoice($1,$2,$3,$4,$5,$6,$7) id',[request,[a],{...header,...opts.header},opts.lines||lines,opts.publish??false,opts.portal??true,opts.invoice??null])).rows[0].id;
const request='60000000-0000-0000-0000-000000000001';
const invoice=await save(request);
assert.equal((await db.query('select count(*) n from invoice_portal_deliveries')).rows[0].n,0,'Drafts queue no customer notification');
await db.exec("set test.actor='70000000-0000-0000-0000-000000000001'");assert.equal((await db.query('select count(*) n from invoices')).rows[0].n,0,'Portal customer cannot see the open draft');await assert.rejects(db.query('select submit_invoice($1)',[invoice]),/Billing permission/);await db.exec("set test.actor=''");
assert.equal(await save(request),invoice,'Same retry returns original invoice');
assert.equal((await db.query('select count(*) n from invoices')).rows[0].n,1);
assert.equal((await db.query('select sum(actual_hours) n,count(*) c from work_order_invoice_links')).rows[0].n,'4.13');
assert.equal((await db.query('select count(*) n from service_billing_queue where invoice_id=$1',[invoice])).rows[0].n,2);
assert.equal((await db.query('select total from invoices')).rows[0].total,'635.00');
assert.equal((await db.query("select notes_visible_on_invoice from invoice_line_items where item_type='material'")).rows[0].notes_visible_on_invoice,false);
await assert.rejects(save('60000000-0000-0000-0000-000000000002'),/already invoiced/);
await assert.rejects(save(request,{invoice,publish:true,header:{notes:'reject'}}),/rejected/);
assert.equal((await db.query('select status from invoices')).rows[0].status,'draft','Rejected publication rolls back');
await db.exec(`insert into time_entries(work_order_id,total_hours,status) values('${b}',0,'draft')`);
await save(request,{invoice});
await assert.rejects(save(request,{invoice,publish:true}),/Clock out/);
await db.exec('delete from time_entries where clock_out is null');
await save(request,{invoice,publish:true,portal:false,lines:[{...lines[0],quantity:4.5},lines[1]]});
assert.equal((await db.query('select total,portal_visible from invoices')).rows[0].total,'660.00');
assert.equal((await db.query('select portal_visible from invoices')).rows[0].portal_visible,false);
assert.equal((await db.query('select sum(total_hours) n from time_entries')).rows[0].n,'4.13','Billing never edits actual time');
await assert.rejects(save(request,{invoice}),/draft invoice/);
await assert.rejects(db.query('update invoice_line_items set quantity=9 where invoice_id=$1',[invoice]),/locked/);
await assert.rejects(db.query("update invoices set total=1,status='overdue' where id=$1",[invoice]),/locked/,'Changing status cannot bypass the accounting lock');
await assert.rejects(db.query("update invoices set status='draft' where id=$1",[invoice]),/Unlock/);
await db.query('select unlock_invoice_for_changes($1,$2)',[invoice,'Correct parts quantity']);
assert.equal((await db.query('select status,portal_visible from invoices')).rows[0].status,'draft');
assert.equal((await db.query('select portal_visible from invoices')).rows[0].portal_visible,false);
await assert.rejects(db.query('update invoices set portal_visible=true where id=$1',[invoice]),/portal/);
await db.query('update invoice_line_items set description=$2 where invoice_id=$1',[invoice,'Corrected service']);
await save(request,{invoice,publish:true});
assert.equal((await db.query('select revision from invoice_portal_deliveries')).rows[0].revision,2,'Resubmission queues a revised notification');
await db.query("update invoices set amount_paid=1,status='partial' where id=$1",[invoice]);
await assert.rejects(db.query('select unlock_invoice_for_changes($1,$2)',[invoice,'Change paid invoice']),/unpaid/);
await assert.rejects(db.query('delete from service_parts_used where id=$1',[part]),/locked/,'Billed source parts cannot be removed through a cascading deletion');
await assert.rejects(db.query('select private.submit_invoice_engine($1)',[invoice]),/permission denied/);
await assert.rejects(db.query('select * from claim_invoice_portal_deliveries()'),/permission denied/);
await db.exec("set test.actor='70000000-0000-0000-0000-000000000001'");assert.equal((await db.query('select count(*) n from invoices')).rows[0].n,1,'Portal customer can see only the submitted invoice');await db.exec("set test.actor=''");
await db.close();console.log('Linked visit, actual hours, selling prices, editable drafts, retry prevention rollback, draft privacy, submission locks and intentional unlock checks passed.');
