/*
  # Fix Kiosk Anonymous Insert - Remove Username Requirement

  1. Changes
    - Remove username requirement from anonymous contacts INSERT policy
    - Username is auto-generated by the application, so shouldn't be required by RLS
    - This fixes the issue where kiosk works when logged in (PC) but not when anonymous (iPad)

  2. Security
    - Anonymous users can only INSERT contacts (no read/update/delete)
    - Still requires essential contact information (email, phone, name)
    - Still requires organization_id to be explicitly provided
    - Prevents malicious bulk inserts by requiring all essential fields
*/

-- Drop the existing policy
DROP POLICY IF EXISTS "Anonymous users can create contacts for kiosk and VIP" ON contacts;

-- Recreate without username requirement
CREATE POLICY "Anonymous users can create contacts for kiosk and VIP"
  ON contacts
  FOR INSERT
  TO anon
  WITH CHECK (
    -- Require email, phone, and name
    email IS NOT NULL
    AND phone IS NOT NULL
    AND (
      contact_name IS NOT NULL
      OR (first_name IS NOT NULL AND last_name IS NOT NULL)
    )
    -- Must provide organization_id explicitly
    AND organization_id IS NOT NULL
  );
