/*
  # Revoke anon EXECUTE on SECURITY DEFINER functions - Batch 4 (s-z)

  Final batch revoking anon role execute privileges from internal SECURITY DEFINER functions.
*/

REVOKE EXECUTE ON FUNCTION public.save_portal_version_snapshot(proposal_id_param uuid, notes_param text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_deposit_request_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_mileage_reminders() FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_po_request_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_punchlist_invite(p_invite_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.send_scheduled_connection_notifications() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_active_revision(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_contact_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_global_admin_status(target_user_id uuid, is_admin boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_invoice_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_job_elr_override(p_sales_order_id uuid, p_override_rate numeric, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_lead_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_manufacturer_company_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_organization_plan(org_id uuid, new_plan_type text, new_plan_tier text, new_max_users integer, new_trial_ends_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_personal_appointment_defaults() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_product_user_tracking() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_project_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_proposal_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_record_office_and_owner() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_recurring_subscription_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_sales_order_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_service_request_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_so_original_contract_total() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_task_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_vendor_company_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_work_order_sales_rep() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_work_order_user_names() FROM anon;
REVOKE EXECUTE ON FUNCTION public.start_user_session(p_user_id uuid, p_ip_address text, p_user_agent text, p_device_type text, p_browser_name text, p_browser_version text, p_os_name text, p_os_version text, p_device_model text, p_device_vendor text, p_organization_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_security_onboarding(p_token text, p_full_name text, p_email text, p_phone text, p_address_line1 text, p_city text, p_state text, p_zip_code text, p_signature text, p_customer_ip text, p_payment_method text, p_payment_token text, p_last_four text, p_emergency_contacts jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_account_credit_remaining() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_is_prospect_flag() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_profile_points() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_vip_appointment_to_work_order() FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_punchlist_access_suspension(p_access_grant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_revision_portal_visibility(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.touch_proposal_on_line_item_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.touch_proposals_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.transfer_change_order_to_proposal(p_change_order_id uuid, p_proposal_title text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_recalc_quota_on_history_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_recalc_quota_on_profile_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_contact_qb_sync() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_recalculate_proposal_totals() FROM anon;
REVOKE EXECUTE ON FUNCTION public.unarchive_work_order(p_work_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.unlink_work_order(p_work_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.unlock_change_order(p_change_order_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.unlock_proposal(proposal_id_param uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_change_order_billing_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_commission_on_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_contact_portal_access(p_contact_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_design_briefs_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_device_nickname_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_internal_time_sessions_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_inventory_on_po_receipt() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_ip_nickname_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_labor_phase_mapping(p_labor_phase_id uuid, p_counts_against_target boolean, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_platform_pricing(p_base_price numeric, p_per_user_price numeric, p_included_users integer, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_project_notes_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_items_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_pricing(p_proposal_id uuid, p_update_pricing boolean, p_convert_discontinued_to_custom boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_readiness() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_settings_readiness() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_unread_count() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_proposal_weekly_notes_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_pto_balance_on_approval() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_review_requests_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_scope_of_work_timestamp() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_security_contract_timestamp() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_session_activity(p_user_id uuid, p_page text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_session_activity(p_user_id uuid, p_page text, p_session_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_session_logout_schedule_timestamp() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_staff_video_library_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_task_comment_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_vehicle_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_can_view_record(target_office_id uuid, target_created_by uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_has_module_access(p_user_id uuid, p_module_key text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_discount_code(p_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_invoice_amount(p_sales_order_id uuid, p_new_invoice_amount numeric, p_exclude_invoice_id uuid) FROM anon;
