/*
  # Revoke anon EXECUTE on SECURITY DEFINER functions - Batch 3 (h-r)

  Continues revoking anon role execute privileges from internal SECURITY DEFINER functions.
*/

REVOKE EXECUTE ON FUNCTION public.handle_deposit_billing_action(p_proposal_id uuid, p_send_notification boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_deposit_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_deposit_payment_completion() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_invoice_paid_deposit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_mileage_entry_submission() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_no_deposit_action(p_proposal_id uuid, p_send_notification boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_po_acceptance_action(p_proposal_id uuid, p_po_number text, p_po_file_url text, p_send_notification boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_proposal_approval() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_proposal_reactivation_request() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_service_request_cancellation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_service_request_completion() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_unified_proposal_approval() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_admin_bypass_rls() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_global_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_manager_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_staff_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_working_today(tech_id uuid, check_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_work_orders(p_work_order_ids uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.lock_proposal(proposal_id_param uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_bonus_calculation_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_change_order_action() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_punchlist_task_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_sms(p_contact_id uuid, p_appointment_id uuid, p_to_phone text, p_message text, p_status text, p_external_id text, p_error text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_workflow_email(p_enrollment_id uuid, p_step_id uuid, p_error text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_abandoned_signups() FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_expired_punchlist_access() FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_proposal_activity_viewed(p_proposal_id uuid, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_punchlist_task_completed(p_task_id uuid, p_completed_by uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_punchlist_task_completed(p_task_id uuid, p_completed_by uuid, p_completed_by_customer boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_reminder_sent(p_appointment_id uuid, p_status text, p_error text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_settings_section_reviewed(proposal_id_input uuid, section_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.midnight_session_cleanup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.monitor_invoice_payment_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_admins_of_vip_signup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_approvers_of_time_request() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_bug_report() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_creator_service_request_kicked_back() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_deposit_completed() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_deposit_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_deposit_request() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_managers_service_request_resubmitted() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_on_customer_question() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_paparazzi_requester() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_pending_deposit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_rep_of_proposal_message() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_sales_rep_of_approval(p_proposal_id uuid, p_customer_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_service_managers_new_request() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_task_assigned() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_task_status_changed() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_tech_of_time_request_outcome() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_time_adjustment_requested() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_watchers_of_comment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_work_order_assignment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.populate_default_starred_modules(p_user_id uuid, p_role text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_stock_adjustment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_stock_transfer() FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_subscription_cancellation(p_subscription_id uuid, p_reason_category text, p_reason_details text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_task_comment_mentions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.promote_revision_to_live(revision_id_param uuid, send_notification boolean, notification_message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_punchlist_invite() FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_sales_quotas() FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_field_target_on_change_order_approval() FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_sales_quota_for_user(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_invoice_open(p_invoice_id uuid, p_user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_invoice_open(p_invoice_id uuid, p_user_agent text, p_event_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_proposal_notification(p_proposal_id uuid, p_notification_type text, p_recipient_email text, p_recipient_name text, p_method text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_scheduled_logout_run(sessions_closed integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_contact_portal_access_cache(p_contact_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_portal_access_on_proposal_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_portal_access_on_subscription_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_sales_monthly_stats(p_user_id uuid, p_org_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_change_order(p_change_order_id uuid, p_rejection_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.renew_punchlist_access(p_access_grant_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reopen_project_task() FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_punchlist_service(p_task_ids uuid[], p_contact_id uuid, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reserve_pto_balance() FROM anon;
REVOKE EXECUTE ON FUNCTION public.restore_portal_version(portal_version_id_param uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.revert_proposal_from_snapshot(p_proposal_id uuid, p_snapshot jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rollback_time_entry_import(p_batch_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rollover_incomplete_occurrences() FROM anon;
