/*
  # Revoke anon EXECUTE on SECURITY DEFINER functions - Batch 2 (d-g)

  Continues revoking anon role execute privileges from internal SECURITY DEFINER functions.
*/

REVOKE EXECUTE ON FUNCTION public.current_user_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.decline_punchlist_invite(p_invite_id uuid, p_decline_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.deduct_manual_entry_points() FROM anon;
REVOKE EXECUTE ON FUNCTION public.duplicate_work_order_to_technician(p_source_work_order_id uuid, p_target_technician_id uuid, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.end_user_session(p_user_id uuid, p_session_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_single_default_calendar() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enroll_in_workflow(p_workflow_id uuid, p_contact_id uuid, p_lead_id uuid, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_single_default_contract() FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_single_default_payment_method() FROM anon;
REVOKE EXECUTE ON FUNCTION public.execute_auto_archive_declined_proposals() FROM anon;
REVOKE EXECUTE ON FUNCTION public.execute_midnight_session_cleanup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.execute_scheduled_logout() FROM anon;
REVOKE EXECUTE ON FUNCTION public.expire_old_proposals() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_batch_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_co_number_per_so() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_combined_task_description(task_ids uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_project_number(p_sales_order_number text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_project_tasks_from_proposal() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_project_tasks_on_project_creation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_proposal_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_recurring_appointments(parent_appointment_id uuid, generate_until date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_recurring_work_orders(parent_work_order_id uuid, generate_until date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_sales_order_number(p_proposal_number text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_scheduled_occurrences() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_statement_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_active_sessions_with_cleanup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_all_punchlist_customers() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_applicable_tax_rate(p_contact_id uuid, p_zip_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_appointments_needing_reminders() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_appointments_with_privacy(p_user_id uuid, p_company_id uuid, p_start_date date, p_end_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_billing_summary(p_sales_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_portal_access_level(p_contact_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_effective_commission_rate(p_employee_id uuid, p_role_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_gps_quality_report(p_technician_id uuid, p_start_date date, p_end_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_latest_technician_locations() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_platform_pricing() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_proposal_activity_summary(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_proposal_payment_methods(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_proposal_sales_order_id(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_proposal_unread_count(p_proposal_id uuid, p_sender_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_punchlist_access_info(p_contact_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_recent_auto_clock_outs(days_ago integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_recently_used_products(p_company_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_root_proposal_id(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_session_logout_schedule() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_tech_efficiency_for_advisor(p_current_start date, p_current_end date, p_prior_start date, p_prior_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_technician_route(p_clock_entry_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_tenant_billing_summary(p_org_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_labor_totals(p_sales_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_project_detail(project_sales_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_project_work_orders(project_sales_order_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_projects(include_expired boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_projects_for_user(p_user_id uuid, include_expired boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_projects_with_variance(p_user_id uuid, p_start_date date, p_end_date date, p_include_expired boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_test_tune_stats_for_user(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_time_entry_project_id(p_time_entry_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_top_performers(days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_upcoming_punchlist_customers() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_accessible_modules(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_calendars(user_id_param uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_device_summary(p_user_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_full_name(user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_location_summary(p_user_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_module_access(p_user_id uuid, p_module_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_org_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_points_balance(user_uuid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_proposal_visibility_scope(user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_test_tune_permissions(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_visibility_scope() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_users_needing_mileage_reminders() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_vehicle_statistics(p_vehicle_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_work_order_group_summary(p_group_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.grant_punchlist_access_directly(p_contact_id uuid, p_days integer, p_notes text) FROM anon;
