// Isolated PostgreSQL engine. No production credentials or customer records needed.
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const uid = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
const org=uid(1), otherOrg=uid(2), user=uid(10), colleague=uid(11), outsider=uid(12), customer=uid(20), otherCustomer=uid(21), project=uid(30), wo=uid(40);
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated;
CREATE SCHEMA auth; GRANT USAGE ON SCHEMA auth,public TO authenticated;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE organizations(id uuid PRIMARY KEY);
CREATE TABLE profiles(id uuid PRIMARY KEY,organization_id uuid,full_name text,role text,role_id uuid);
CREATE FUNCTION get_user_org_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path='public' AS $$ SELECT organization_id FROM profiles WHERE id=auth.uid() $$;
CREATE TABLE department_modules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),module_key text,display_name text,is_active boolean DEFAULT true);
CREATE TABLE role_module_access(role_id uuid,module_id uuid,has_access boolean);
CREATE TABLE user_permission_overrides(user_id uuid,module_id uuid,override_type text);
CREATE TABLE contacts(id uuid PRIMARY KEY,organization_id uuid,full_name text,contact_name text,company_name text,assigned_to uuid,office_id uuid,phone text,updated_at timestamptz DEFAULT now());
CREATE TABLE projects(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,name text,project_number text,assigned_pm uuid,salesperson_id uuid,designer_id uuid,office_id uuid,customer_location_id uuid,status text,created_at timestamptz DEFAULT now());
CREATE TABLE work_orders(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,project_id uuid,work_order_number text,title text,assigned_to uuid,customer_sales_rep_id uuid,office_id uuid,customer_location_id uuid,status text,scheduled_date date,scheduled_start_time time,description text,updated_at timestamptz,created_at timestamptz DEFAULT now());
CREATE TABLE customer_locations(id uuid PRIMARY KEY,customer_contact_id uuid,name text);
CREATE TABLE service_requests(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,project_id uuid,work_order_id uuid,status text);
CREATE TABLE change_orders(id uuid PRIMARY KEY,organization_id uuid,project_id uuid,change_order_number text,status text,description text);
CREATE TABLE product_requests(id uuid PRIMARY KEY,organization_id uuid,work_order_id uuid,project_id uuid,customer_contact_id uuid,status text);
CREATE TABLE proposals(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,proposal_number text,status text);
CREATE TABLE invoices(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,project_id uuid,office_id uuid,invoice_number text,status text);
CREATE TABLE payments(id uuid PRIMARY KEY,organization_id uuid,invoice_id uuid);
CREATE TABLE project_notes(id uuid PRIMARY KEY,organization_id uuid,project_id uuid,body text,is_internal boolean);
CREATE TABLE customer_contact_log(id uuid PRIMARY KEY,organization_id uuid,work_order_id uuid,service_request_id uuid,notes text);
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO authenticated;
INSERT INTO organizations VALUES ('${org}'),('${otherOrg}');
INSERT INTO profiles VALUES ('${user}','${org}','Josh','admin',null),('${colleague}','${org}','Jesse','admin',null),('${outsider}','${otherOrg}','Other dealer','admin',null);
INSERT INTO department_modules(module_key) SELECT unnest(ARRAY['contacts','projects','work_orders','service_requests','change_orders','parts_requests','proposals','invoices']);
INSERT INTO contacts(id,organization_id,full_name,assigned_to) VALUES ('${customer}','${org}','Jones Residence','${colleague}'),('${otherCustomer}','${otherOrg}','Other customer','${outsider}');
INSERT INTO projects(id,organization_id,contact_id,name,project_number,assigned_pm) VALUES ('${project}','${org}','${customer}','Jones installation','P-100','${colleague}');
`);
const migration = await readFile(new URL('../../supabase/migrations/20260928183403_customer_job_flow.sql',import.meta.url),'utf8');
await db.exec(migration);
async function asUser(id) { await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${id}'; SET ROLE authenticated;`); }
async function list(filters={}, before=null) { return (await db.query('SELECT * FROM get_flow_events($1,$2,50)',[JSON.stringify(filters),before])).rows.map(r=>r.get_flow_events); }
async function rejects(sql, message) { await assert.rejects(db.exec(sql), undefined, message); }
await asUser(user);
await db.exec(`INSERT INTO work_orders(id,organization_id,contact_id,project_id,work_order_number,title,assigned_to,status) VALUES('${wo}','${org}','${customer}','${project}','1842','TV replacement','${colleague}','pending')`);
let events=await list(); assert.equal(events.length,1); assert.equal(events[0].actor_name,'Josh');
assert.equal((await list({contact_id:customer}))[0].id,events[0].id);
assert.equal((await list({project_id:project}))[0].id,events[0].id);
assert.equal((await list({work_order_id:wo}))[0].id,events[0].id);
await db.exec(`UPDATE work_orders SET updated_at=now() WHERE id='${wo}'`); assert.equal((await list()).length,1,'Non-business writes produce no event');
await db.exec(`UPDATE work_orders SET status='scheduled',scheduled_date='2026-09-25',scheduled_start_time='10:00' WHERE id='${wo}'`);
events=await list(); assert.equal(events.length,2,'Multiple changes in one update produce one row'); assert.equal(events[0].category,'scheduling'); assert.match(events[0].details,/2026-09-25/);
await db.exec(`INSERT INTO flow_event_views(event_id) VALUES (${events[0].id})`);
assert.equal((await list())[0].viewed,true); assert.equal((await list({new_only:true})).length,1);
await asUser(colleague); assert.equal((await list({my_work:true})).length,2,'Assigned PM and tech receive My Work'); assert.equal((await list())[0].viewed,false,'Viewed state is personal');
await db.exec(`INSERT INTO flow_updates(organization_id,work_order_id,body,update_type) VALUES('${org}','${wo}','Working with Luis on the TV','working_issue')`);
events=await list(); assert.equal(events[0].contact_id,customer); assert.equal(events[0].project_id,project); assert.match(events[0].summary,/Working Issue/);
await rejects(`INSERT INTO flow_updates(organization_id,contact_id,work_order_id,body) VALUES('${org}','${otherCustomer}','${wo}','Mismatch')`,'Mismatched customer rejected');
await rejects(`INSERT INTO flow_updates(organization_id,contact_id,body) VALUES('${org}','${otherCustomer}','Wrong dealer')`,'Cross-tenant reference rejected');
await rejects(`INSERT INTO flow_updates(organization_id,contact_id,body) VALUES('${otherOrg}','${otherCustomer}','Wrong dealer')`,'Cross-tenant organization rejected');
await rejects(`DELETE FROM flow_events`,'Event deletion denied');
await rejects(`INSERT INTO flow_events(organization_id,actor_name,category,event_type,summary,source_table,source_id,required_module) VALUES('${org}','Fake','work','fake','fake','work_orders','${wo}','work_orders')`,'Event forgery denied');
await asUser(outsider); assert.equal((await list()).length,0,'Other dealer cannot read events');
await rejects(`INSERT INTO flow_event_views(event_id) VALUES(${events[0].id})`,'Cannot mark inaccessible events');
await asUser(uid(999)); assert.equal((await list()).length,0,'Portal user without employee profile sees nothing');
await asUser(user);
await db.exec(`INSERT INTO service_requests(id,organization_id,contact_id,status) VALUES('${uid(50)}','${org}','${customer}','pending')`);
assert.equal((await list({category:'service'})).length,1,'Standalone service request reaches customer Flow');
await db.exec(`INSERT INTO work_orders(id,organization_id,contact_id,work_order_number,title,assigned_to,status) VALUES('${uid(41)}','${org}','${customer}','1843','Service only','${colleague}','pending')`);
const standalone=await list({work_order_id:uid(41)}); assert.equal(standalone.length,1); assert.equal(standalone[0].project_id,null);
await db.exec(`INSERT INTO invoices VALUES('${uid(60)}','${org}','${customer}','${project}',null,'INV-1','sent')`);
await db.exec(`INSERT INTO payments VALUES('${uid(61)}','${org}','${uid(60)}')`);
assert.equal((await list({category:'financial'})).length,2);
await db.exec(`INSERT INTO user_permission_overrides SELECT '${colleague}',id,'revoke' FROM department_modules WHERE module_key='invoices'`);
await asUser(colleague); assert.equal((await list({category:'financial'})).length,0,'Explicit revoke wins even for admin');
await asUser(user);
await db.exec(`INSERT INTO project_notes VALUES('${uid(70)}','${org}','${project}','Secret note',true)`);
await db.exec(`RESET ROLE; UPDATE profiles SET role='tech',role_id='${uid(80)}' WHERE id='${colleague}'; INSERT INTO role_module_access SELECT '${uid(80)}',id,true FROM department_modules;`);
await asUser(colleague); assert.ok(!(await list()).some(e=>e.source_id===uid(70)),'Restricted notes stay hidden from techs');
assert.equal((await list({search:'TV replacement'})).length,0,'Search matches snapshotted display fields only');
assert.ok((await list({search:'Jones'})).length>0);
const all=await list(); const later=await list({},all[2].id); assert.ok(later.every(e=>e.id<all[2].id),'Cursor excludes already loaded rows');
const targets=(await db.query('SELECT * FROM search_flow_targets($1,null)',['Jones'])).rows; assert.ok(targets.length>=2,'Picker finds customer and project');
await asUser(user);
const before=(await list()).length;
await db.exec(`BEGIN; UPDATE work_orders SET status='completed' WHERE id='${wo}'; ROLLBACK;`);
assert.equal((await list()).length,before,'Rolled back work cannot leave a Flow event');
await asUser(user);
await db.exec(`INSERT INTO change_orders VALUES('${uid(90)}','${org}','${project}','CO-1','draft','TV'); UPDATE change_orders SET status='approved' WHERE id='${uid(90)}';
INSERT INTO product_requests VALUES('${uid(91)}','${org}','${wo}','${project}',null,'pending'); UPDATE product_requests SET status='received' WHERE id='${uid(91)}';
INSERT INTO proposals VALUES('${uid(92)}','${org}','${customer}','PRO-1','draft'); UPDATE proposals SET status='sent' WHERE id='${uid(92)}';
INSERT INTO customer_contact_log VALUES('${uid(93)}','${org}','${wo}',null,'Call notes');
UPDATE contacts SET phone='555-0100' WHERE id='${customer}'; UPDATE projects SET status='active' WHERE id='${project}';`);
const sources=new Set((await list()).map(e=>e.source_table));
for(const source of ['work_orders','projects','service_requests','change_orders','product_requests','proposals','invoices','payments','contacts','project_notes','customer_contact_log','flow_updates']) assert.ok(sources.has(source),source+' captured');
await db.exec(`INSERT INTO department_modules(module_key) VALUES('invoices'); INSERT INTO role_module_access SELECT '${uid(80)}',id,true FROM department_modules WHERE module_key='invoices' AND id NOT IN (SELECT module_id FROM role_module_access);`);
await asUser(colleague); assert.equal((await list({category:'financial'})).length,0,'Revocation wins across duplicate module keys');
console.log('PASS: source events, standalone service, shared scopes, concise transitions, My Work, personal views, pagination, atomicity, tenant isolation, forgery prevention, module overrides, restricted notes, and target search.');
await db.exec(`RESET ROLE;
 ALTER TABLE profiles ADD COLUMN contact_id uuid; ALTER TABLE profiles ADD COLUMN username text;
 ALTER TABLE contacts ADD COLUMN portal_user_id uuid;
 ALTER TABLE proposals ADD COLUMN created_by uuid;
 CREATE TABLE message_threads(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,proposal_id uuid,context_type text,context_id uuid,created_by uuid,assigned_sales_rep_id uuid,visibility text DEFAULT 'public');
 CREATE TABLE messages(id uuid PRIMARY KEY,organization_id uuid,thread_id uuid,author_id uuid,author_name text,author_type text,body text,is_internal boolean,created_at timestamptz DEFAULT now());
 CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid,user_id uuid,type text,title text,body text,related_id uuid,is_read boolean);
 CREATE TABLE tasks(id uuid PRIMARY KEY,organization_id uuid,contact_id uuid,user_id uuid,assigned_to uuid,title text,status text,created_at timestamptz DEFAULT now());
 CREATE TABLE task_comments(id uuid PRIMARY KEY,organization_id uuid,task_id uuid,user_id uuid,content text,created_at timestamptz DEFAULT now());
 CREATE TABLE discussion_posts(id uuid PRIMARY KEY,organization_id uuid,user_id uuid,assigned_to uuid,content text,mentions text[] DEFAULT '{}',is_private boolean DEFAULT false,post_type text,parent_id uuid,created_at timestamptz DEFAULT now());
 ALTER TABLE message_threads ENABLE ROW LEVEL SECURITY; ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
 GRANT SELECT ON message_threads,messages,notifications,tasks,task_comments,discussion_posts TO authenticated;
 UPDATE profiles SET role='sales',username='jg' WHERE id='${user}';
 UPDATE profiles SET username='jesse' WHERE id='${colleague}';
 INSERT INTO profiles(id,organization_id,full_name,role,username) VALUES('${uid(13)}','${org}','Unrelated rep','sales','rep');
 INSERT INTO department_modules(module_key) VALUES('messages'),('tasks'),('feed');
 INSERT INTO role_module_access SELECT '${uid(80)}',id,true FROM department_modules WHERE module_key IN ('messages','tasks','feed');
 INSERT INTO message_threads(id,organization_id,contact_id,proposal_id,context_type,context_id,created_by,assigned_sales_rep_id)
 VALUES('${uid(100)}','${org}','${customer}',null,'project','${project}','${colleague}','${user}');
 INSERT INTO message_threads(id,organization_id,contact_id,proposal_id,context_type,context_id,created_by,assigned_sales_rep_id)
 VALUES('${uid(101)}','${otherOrg}','${otherCustomer}',null,'contact','${otherCustomer}','${outsider}',null);
`);
const communications = await readFile(new URL('../../supabase/migrations/20260928200000_my_flow_customer_conversations.sql',import.meta.url),'utf8');
await db.exec(communications);
await asUser(user);
await db.exec('RESET ROLE;');
await db.exec(`INSERT INTO messages(id,organization_id,thread_id,author_id,author_name,author_type,body,is_internal)
 VALUES('${uid(102)}','${org}','${uid(100)}','${user}','Josh','staff','Right @Jesse! Please check this.',true)`);
await asUser(user);
const mentioned = await list({mentions_only:true,my_work:true});
assert.equal(mentioned.length,0,'The author is not mentioned by their own message');
await asUser(colleague);
const jesseMentions = await list({mentions_only:true,my_work:true});
assert.equal(jesseMentions.length,1,'An exact handle highlights the conversation for its recipient');
assert.equal(jesseMentions[0].thread_id,uid(100));
assert.equal(jesseMentions[0].details,'Open the conversation to read the message in context.');
assert.equal((await db.query('SELECT count(*)::int AS count FROM notifications WHERE user_id=$1',[colleague])).rows[0].count,1);
await asUser(uid(13));
assert.equal((await list({category:'communication'})).length,0,'A rep outside this customer cannot read its Flow conversation');
assert.equal((await db.query('SELECT count(*)::int AS count FROM messages')).rows[0].count,0,'The thread RLS also hides message bodies');
await assert.rejects(db.exec(`UPDATE profiles SET can_view_all_messages=true WHERE id='${uid(13)}'`),
  /Only an organization admin/, 'A user cannot grant themselves executive access');
await db.exec(`RESET ROLE; SET request.jwt.claim.sub='';`);
await db.exec(`UPDATE profiles SET can_view_all_messages=true WHERE id='${uid(13)}'`);
await asUser(uid(13));
assert.equal((await list({category:'communication'})).length,1,'Explicit executive access covers company conversations');
assert.equal((await list({category:'communication',my_work:true})).length,0,'Executive oversight does not turn every thread into personal work');
assert.equal((await list({kind:'messages'})).length,1,'Messages category includes its conversation');
assert.equal((await list({kind:'tasks'})).length,0,'Tasks filter excludes messages');
assert.equal((await list({kind:'activity'})).length,0,'Executive message access does not grant unrelated activity modules');

await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}';
 INSERT INTO tasks(id,organization_id,contact_id,user_id,assigned_to,title,status)
 VALUES('${uid(110)}','${org}','${customer}','${user}','${colleague}','Check rack','pending');
 INSERT INTO task_comments(id,organization_id,task_id,user_id,content)
 VALUES('${uid(111)}','${org}','${uid(110)}','${user}','Parts arrived for @jesse');
 INSERT INTO discussion_posts(id,organization_id,user_id,assigned_to,content,post_type)
 VALUES('${uid(112)}','${org}','${user}','${colleague}','Right @jesse?','question');`);
await asUser(colleague);
const relatedComms = await list({category:'communication',my_work:true});
assert.ok(relatedComms.some(e=>e.source_table==='tasks' && e.source_id===uid(110)),'Assigned customer tasks appear');
assert.ok(relatedComms.some(e=>e.source_table==='task_comments' && e.task_id===uid(110) && e.preview?.includes('Parts arrived')),'Task comments preview and open their parent task');
assert.ok(relatedComms.some(e=>e.source_table==='discussion_posts' && e.mentioned_user_ids.includes(colleague)),'Discussion mentions are highlighted');
assert.equal((await db.query("SELECT count(*)::int AS count FROM notifications WHERE user_id=$1 AND type='discussion_post_mention'",[colleague])).rows[0].count,1,'Discussion mentions notify with a direct post link');

await db.exec(`RESET ROLE; SET request.jwt.claim.sub=''; UPDATE contacts SET assigned_to='${user}' WHERE id='${customer}';
 INSERT INTO projects(id,organization_id,contact_id,name,project_number,salesperson_id,status)
 VALUES('${uid(31)}','${org}','${customer}','Other rep project','P-101','${colleague}','draft');`);
await asUser(colleague);
await db.exec(`UPDATE projects SET status='active' WHERE id='${uid(31)}'`);
await asUser(user);
assert.ok(!(await list({my_work:true})).some(e=>e.project_id===uid(31)),'Customer owner does not inherit another rep project activity');
assert.ok(!(await list()).some(e=>e.project_id===uid(31)),'All Activity still respects project module access');
assert.equal((await list({kind:'discussions'})).filter(e=>e.source_table!=='discussion_posts').length,0,'Discussion filter is exact');
await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}';
 INSERT INTO discussion_posts(id,organization_id,user_id,content,post_type,project_id)
 VALUES('${uid(113)}','${org}','${user}','Status for #Jones installation','general','${project}');
 INSERT INTO discussion_posts(id,organization_id,user_id,content,post_type,parent_id)
 VALUES('${uid(115)}','${org}','${user}','Reply on this job','general','${uid(113)}');
 INSERT INTO flow_updates(organization_id,project_id,body)
 VALUES('${org}','${project}','@jesse Can you confirm the schedule?');`);
await asUser(colleague);
assert.ok((await list({project_id:project,kind:'discussions'})).some(e=>e.source_id===uid(113)),'Chosen project is attached to its Flow');
assert.ok((await list({project_id:project,kind:'discussions'})).some(e=>e.source_id===uid(115)),'Replies inherit the project destination');
assert.ok((await list({project_id:project,mentions_only:true})).some(e=>e.source_table==='flow_updates'),'Flow update @handle is a direct mention');
const mentionedUpdate=(await list({project_id:project,mentions_only:true})).find(e=>e.source_table==='flow_updates');
assert.equal((await list({source_id:mentionedUpdate.source_id})).length,1,'Mention link selects the exact update');
assert.equal((await db.query("SELECT count(*)::int AS count FROM notifications WHERE user_id=$1 AND type='flow_update_mention'",[colleague])).rows[0].count,1,'Flow update mention notifies once');
await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}';`);
await rejects(`INSERT INTO discussion_posts(id,organization_id,user_id,content,post_type,project_id) VALUES('${uid(114)}','${org}','${user}','Wrong dealer','general','${uid(999)}')`,'Invalid project tag rejected');
await asUser(outsider);
assert.equal((await list({category:'communication'})).length,0,'Another dealer cannot see the thread');
console.log('PASS: related conversation, mention routing, context link, no body snapshot, and tenant isolation.');
await db.close();
